/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getBulkArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-bulk-archive-change',
    description: '一次性归档多个已完成的变更。当需要归档多个并行变更时使用。',
    instructions: `一次性归档多个已完成的变更。

此技能允许你批量归档变更，通过检查代码库确定实际实现情况来智能处理规范冲突。

**输入**：无需输入（会提示选择）

**步骤**

1. **获取活跃变更**

   运行 \`openspec-cn list --json\` 获取所有活跃变更。

   如果没有活跃变更，通知用户并停止。

2. **提示选择变更**

   使用 **AskUserQuestion tool** 的多选功能让用户选择变更：
   - 显示每个变更及其 Schema
   - 包含"所有变更"选项
   - 允许任意数量的选择（1+ 可行，2+ 是典型用例）

   **重要**：不要自动选择。始终让用户选择。

3. **批量验证 - 收集所有选中变更的状态**

   对每个选中的变更，收集：

   a. **产出物状态** - 运行 \`openspec-cn status --change "<name>" --json\`
      - 解析 \`schemaName\`、\`artifacts\`、\`planningHome\`、\`changeRoot\`、\`artifactPaths\` 和 \`actionContext\`
      - 记录哪些产出物是 \`done\` 和其他状态

      如果任何选中的变更报告 \`actionContext.mode: "workspace-planning"\`，说明工作区批量归档在当前版本中不支持并停止，不要在同步规范或移动变更之前继续。不要回退到仓库本地路径或编辑链接的仓库。

   b. **任务完成情况** - 读取状态 JSON 中的 \`artifactPaths.tasks.existingOutputPaths\`
      - 统计 \`- [ ]\`（未完成）和 \`- [x]\`（已完成）
      - 如果没有任务文件，标记为"无任务"

   c. **增量规范** - 检查状态 JSON 中的 \`artifactPaths.specs.existingOutputPaths\`
      - 列出存在哪些能力规范
      - 对每个规范，提取需求名称（匹配 \`### Requirement: <name>\` 的行）

4. **检测规范冲突**

   构建 \`capability -> [涉及的变更]\` 映射：

   \`\`\`
   auth -> [change-a, change-b]  <- 冲突（2+ 个变更）
   api  -> [change-c]            <- 正常（仅 1 个变更）
   \`\`\`

   当 2+ 个选中的变更对同一能力有增量规范时，即存在冲突。

5. **代理式解决冲突**

   **对每个冲突**，调查代码库：

   a. **读取增量规范** 了解每个冲突变更声称添加/修改了什么

   b. **搜索代码库** 寻找实现证据：
      - 查找实现每个增量规范中需求的代码
      - 检查相关文件、函数或测试

   c. **确定解决方案**：
      - 如果只有一个变更实际实现了 -> 同步那个变更的规范
      - 如果两个都实现了 -> 按时间顺序应用（旧的先，新的覆盖）
      - 如果都未实现 -> 跳过规范同步，警告用户

   d. **记录每个冲突的解决方案**：
      - 应用哪个变更的规范
      - 以什么顺序（如果两个都需要）
      - 理由（在代码库中发现了什么）

6. **显示综合状态表**

   显示汇总所有变更的表格：

   \`\`\`
   | 变更                | 产出物    | 任务  | 规范    | 冲突      | 状态   |
   |---------------------|-----------|-------|---------|-----------|--------|
   | schema-management   | 完成      | 5/5   | 2 增量  | 无        | 就绪   |
   | project-config      | 完成      | 3/3   | 1 增量  | 无        | 就绪   |
   | add-oauth           | 完成      | 4/4   | 1 增量  | auth (!)  | 就绪*  |
   | add-verify-skill    | 剩余 1   | 2/5   | 无      | 无        | 警告   |
   \`\`\`

   对冲突，显示解决方案：
   \`\`\`
   * 冲突解决方案：
     - auth 规范：将先应用 add-oauth 再应用 add-jwt（两者都已实现，按时间顺序）
   \`\`\`

   对未完成的变更，显示警告：
   \`\`\`
   警告：
   - add-verify-skill：1 个未完成的产出物，3 个未完成的任务
   \`\`\`

7. **确认批量操作**

   使用 **AskUserQuestion tool** 进行单次确认：

   - "归档 N 个变更？"根据状态提供选项
   - 选项可能包括：
     - "归档全部 N 个变更"
     - "仅归档 N 个就绪变更（跳过未完成的）"
     - "取消"

   如果有未完成的变更，明确说明它们将带警告归档。

8. **对每个确认的变更执行归档**

   按确定的顺序处理变更（遵循冲突解决方案）：

   a. **同步规范** 如果增量规范存在：
      - 使用 openspec-sync-specs 方式（代理驱动智能合并）
      - 对冲突，按解决后的顺序应用
      - 跟踪是否已同步

   b. **执行归档**：
      \`\`\`bash
      mkdir -p "<planningHome.changesDir>/archive"
      mv "<changeRoot>" "<planningHome.changesDir>/archive/YYYY-MM-DD-<name>"
      \`\`\`

   c. **跟踪每个变更的结果**：
      - 成功：归档成功
      - 失败：归档时出错（记录错误）
      - 跳过：用户选择不归档（如果适用）

9. **显示摘要**

   显示最终结果：

   \`\`\`
   ## 批量归档完成

   已归档 3 个变更：
   - schema-management-cli -> archive/2026-01-19-schema-management-cli/
   - project-config -> archive/2026-01-19-project-config/
   - add-oauth -> archive/2026-01-19-add-oauth/

   跳过 1 个变更：
   - add-verify-skill（用户选择不归档未完成的）

   规范同步摘要：
   - 4 个增量规范已同步到主规范
   - 1 个冲突已解决（auth：按时间顺序应用两者）
   \`\`\`

   如果有失败：
   \`\`\`
   失败 1 个变更：
   - some-change：归档目录已存在
   \`\`\`

**冲突解决示例**

示例 1：只有一个已实现
\`\`\`
冲突：specs/auth/spec.md 被 [add-oauth, add-jwt] 修改

检查 add-oauth：
- 增量规范添加"OAuth Provider Integration"需求
- 搜索代码库... 在 src/auth/oauth.ts 中找到 OAuth 流程实现

检查 add-jwt：
- 增量规范添加"JWT Token Handling"需求
- 搜索代码库... 未找到 JWT 实现

解决方案：只有 add-oauth 已实现。仅同步 add-oauth 的规范。
\`\`\`

示例 2：两个都已实现
\`\`\`
冲突：specs/api/spec.md 被 [add-rest-api, add-graphql] 修改

检查 add-rest-api（创建于 2026-01-10）：
- 增量规范添加"REST Endpoints"需求
- 搜索代码库... 在 src/api/rest.ts 中找到

检查 add-graphql（创建于 2026-01-15）：
- 增量规范添加"GraphQL Schema"需求
- 搜索代码库... 在 src/api/graphql.ts 中找到

解决方案：两者都已实现。将先应用 add-rest-api 规范，
再应用 add-graphql 规范（按时间顺序，新的优先）。
\`\`\`

**成功输出**

\`\`\`
## 批量归档完成

已归档 N 个变更：
- <change-1> -> archive/YYYY-MM-DD-<change-1>/
- <change-2> -> archive/YYYY-MM-DD-<change-2>/

规范同步摘要：
- N 个增量规范已同步到主规范
- 无冲突（或：M 个冲突已解决）
\`\`\`

**部分成功输出**

\`\`\`
## 批量归档完成（部分）

已归档 N 个变更：
- <change-1> -> archive/YYYY-MM-DD-<change-1>/

跳过 M 个变更：
- <change-2>（用户选择不归档未完成的）

失败 K 个变更：
- <change-3>：归档目录已存在
\`\`\`

**无变更时输出**

\`\`\`
## 无可归档变更

未找到活跃变更。创建一个新变更以开始。
\`\`\`

**护栏**
- 允许任意数量的变更（1+ 可行，2+ 是典型用例）
- 始终提示选择，永不自动选择
- 尽早检测规范冲突并通过检查代码库解决
- 当两个变更都已实现时，按时间顺序应用规范
- 仅在实现缺失时跳过规范同步（警告用户）
- 确认前显示清晰的每个变更状态
- 整个批次使用单次确认
- 跟踪并报告所有结果（成功/跳过/失败）
- 移动到归档时保留 .openspec.yaml
- 归档目录目标使用当前日期：YYYY-MM-DD-<name>
- 如果归档目标已存在，该变更失败但继续处理其他变更`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxBulkArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Bulk Archive',
    description: '一次性归档多个已完成的变更',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental', 'bulk'],
    content: `一次性归档多个已完成的变更。

此技能允许你批量归档变更，通过检查代码库确定实际实现情况来智能处理规范冲突。

**输入**：无需输入（会提示选择）

**步骤**

1. **获取活跃变更**

   运行 \`openspec-cn list --json\` 获取所有活跃变更。

   如果没有活跃变更，通知用户并停止。

2. **提示选择变更**

   使用 **AskUserQuestion tool** 的多选功能让用户选择变更：
   - 显示每个变更及其 Schema
   - 包含"所有变更"选项
   - 允许任意数量的选择（1+ 可行，2+ 是典型用例）

   **重要**：不要自动选择。始终让用户选择。

3. **批量验证 - 收集所有选中变更的状态**

   对每个选中的变更，收集：

   a. **产出物状态** - 运行 \`openspec-cn status --change "<name>" --json\`
      - 解析 \`schemaName\`、\`artifacts\`、\`planningHome\`、\`changeRoot\`、\`artifactPaths\` 和 \`actionContext\`
      - 记录哪些产出物是 \`done\` 和其他状态

      如果任何选中的变更报告 \`actionContext.mode: "workspace-planning"\`，说明工作区批量归档在当前版本中不支持并停止，不要在同步规范或移动变更之前继续。不要回退到仓库本地路径或编辑链接的仓库。

   b. **任务完成情况** - 读取状态 JSON 中的 \`artifactPaths.tasks.existingOutputPaths\`
      - 统计 \`- [ ]\`（未完成）和 \`- [x]\`（已完成）
      - 如果没有任务文件，标记为"无任务"

   c. **增量规范** - 检查状态 JSON 中的 \`artifactPaths.specs.existingOutputPaths\`
      - 列出存在哪些能力规范
      - 对每个规范，提取需求名称（匹配 \`### Requirement: <name>\` 的行）

4. **检测规范冲突**

   构建 \`capability -> [涉及的变更]\` 映射：

   \`\`\`
   auth -> [change-a, change-b]  <- 冲突（2+ 个变更）
   api  -> [change-c]            <- 正常（仅 1 个变更）
   \`\`\`

   当 2+ 个选中的变更对同一能力有增量规范时，即存在冲突。

5. **代理式解决冲突**

   **对每个冲突**，调查代码库：

   a. **读取增量规范** 了解每个冲突变更声称添加/修改了什么

   b. **搜索代码库** 寻找实现证据：
      - 查找实现每个增量规范中需求的代码
      - 检查相关文件、函数或测试

   c. **确定解决方案**：
      - 如果只有一个变更实际实现了 -> 同步那个变更的规范
      - 如果两个都实现了 -> 按时间顺序应用（旧的先，新的覆盖）
      - 如果都未实现 -> 跳过规范同步，警告用户

   d. **记录每个冲突的解决方案**：
      - 应用哪个变更的规范
      - 以什么顺序（如果两个都需要）
      - 理由（在代码库中发现了什么）

6. **显示综合状态表**

   显示汇总所有变更的表格：

   \`\`\`
   | 变更                | 产出物    | 任务  | 规范    | 冲突      | 状态   |
   |---------------------|-----------|-------|---------|-----------|--------|
   | schema-management   | 完成      | 5/5   | 2 增量  | 无        | 就绪   |
   | project-config      | 完成      | 3/3   | 1 增量  | 无        | 就绪   |
   | add-oauth           | 完成      | 4/4   | 1 增量  | auth (!)  | 就绪*  |
   | add-verify-skill    | 剩余 1   | 2/5   | 无      | 无        | 警告   |
   \`\`\`

   对冲突，显示解决方案：
   \`\`\`
   * 冲突解决方案：
     - auth 规范：将先应用 add-oauth 再应用 add-jwt（两者都已实现，按时间顺序）
   \`\`\`

   对未完成的变更，显示警告：
   \`\`\`
   警告：
   - add-verify-skill：1 个未完成的产出物，3 个未完成的任务
   \`\`\`

7. **确认批量操作**

   使用 **AskUserQuestion tool** 进行单次确认：

   - "归档 N 个变更？"根据状态提供选项
   - 选项可能包括：
     - "归档全部 N 个变更"
     - "仅归档 N 个就绪变更（跳过未完成的）"
     - "取消"

   如果有未完成的变更，明确说明它们将带警告归档。

8. **对每个确认的变更执行归档**

   按确定的顺序处理变更（遵循冲突解决方案）：

   a. **同步规范** 如果增量规范存在：
      - 使用 openspec-sync-specs 方式（代理驱动智能合并）
      - 对冲突，按解决后的顺序应用
      - 跟踪是否已同步

   b. **执行归档**：
      \`\`\`bash
      mkdir -p "<planningHome.changesDir>/archive"
      mv "<changeRoot>" "<planningHome.changesDir>/archive/YYYY-MM-DD-<name>"
      \`\`\`

   c. **跟踪每个变更的结果**：
      - 成功：归档成功
      - 失败：归档时出错（记录错误）
      - 跳过：用户选择不归档（如果适用）

9. **显示摘要**

   显示最终结果：

   \`\`\`
   ## 批量归档完成

   已归档 3 个变更：
   - schema-management-cli -> archive/2026-01-19-schema-management-cli/
   - project-config -> archive/2026-01-19-project-config/
   - add-oauth -> archive/2026-01-19-add-oauth/

   跳过 1 个变更：
   - add-verify-skill（用户选择不归档未完成的）

   规范同步摘要：
   - 4 个增量规范已同步到主规范
   - 1 个冲突已解决（auth：按时间顺序应用两者）
   \`\`\`

   如果有失败：
   \`\`\`
   失败 1 个变更：
   - some-change：归档目录已存在
   \`\`\`

**冲突解决示例**

示例 1：只有一个已实现
\`\`\`
冲突：specs/auth/spec.md 被 [add-oauth, add-jwt] 修改

检查 add-oauth：
- 增量规范添加"OAuth Provider Integration"需求
- 搜索代码库... 在 src/auth/oauth.ts 中找到 OAuth 流程实现

检查 add-jwt：
- 增量规范添加"JWT Token Handling"需求
- 搜索代码库... 未找到 JWT 实现

解决方案：只有 add-oauth 已实现。仅同步 add-oauth 的规范。
\`\`\`

示例 2：两个都已实现
\`\`\`
冲突：specs/api/spec.md 被 [add-rest-api, add-graphql] 修改

检查 add-rest-api（创建于 2026-01-10）：
- 增量规范添加"REST Endpoints"需求
- 搜索代码库... 在 src/api/rest.ts 中找到

检查 add-graphql（创建于 2026-01-15）：
- 增量规范添加"GraphQL Schema"需求
- 搜索代码库... 在 src/api/graphql.ts 中找到

解决方案：两者都已实现。将先应用 add-rest-api 规范，
再应用 add-graphql 规范（按时间顺序，新的优先）。
\`\`\`

**成功输出**

\`\`\`
## 批量归档完成

已归档 N 个变更：
- <change-1> -> archive/YYYY-MM-DD-<change-1>/
- <change-2> -> archive/YYYY-MM-DD-<change-2>/

规范同步摘要：
- N 个增量规范已同步到主规范
- 无冲突（或：M 个冲突已解决）
\`\`\`

**部分成功输出**

\`\`\`
## 批量归档完成（部分）

已归档 N 个变更：
- <change-1> -> archive/YYYY-MM-DD-<change-1>/

跳过 M 个变更：
- <change-2>（用户选择不归档未完成的）

失败 K 个变更：
- <change-3>：归档目录已存在
\`\`\`

**无变更时输出**

\`\`\`
## 无可归档变更

未找到活跃变更。创建一个新变更以开始。
\`\`\`

**护栏**
- 允许任意数量的变更（1+ 可行，2+ 是典型用例）
- 始终提示选择，永不自动选择
- 尽早检测规范冲突并通过检查代码库解决
- 当两个变更都已实现时，按时间顺序应用规范
- 仅在实现缺失时跳过规范同步（警告用户）
- 确认前显示清晰的每个变更状态
- 整个批次使用单次确认
- 跟踪并报告所有结果（成功/跳过/失败）
- 移动到归档时保留 .openspec.yaml
- 归档目录目标使用当前日期：YYYY-MM-DD-<name>
- 如果归档目标已存在，该变更失败但继续处理其他变更`
  };
}
