/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getBulkArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-bulk-archive-change',
    description: '一次性归档多个已完成的变更。当需要归档多个并行变更时使用。',
    instructions: `在单次操作中归档多个已完成的变更。

此技能允许您批量归档变更，通过检查代码库判断实际已实现的内容，从而智能处理 spec 冲突。

${STORE_SELECTION_GUIDANCE}

\`<capability-path>\` 是相对于 \`specs/\` 的 spec 目录（例如 \`user-auth\` 或 \`identity/user-auth\`）。在解析主 spec 时保留每个增量 spec 的完整路径。

**Input**: None required（通过提示选择）

**步骤**

1. **获取活跃变更**

   运行 \`openspec-cn list --json\` 获取所有活跃变更。

   若无活跃变更，告知用户并停止。

2. **提示选择变更**

   请用户选择变更（多选）：
   - 展示每个变更及其 schema
   - 包含"全部变更"选项
   - 允许任意数量的选择（1+ 可以，2+ 是典型用例）

   **重要提示**：切勿自动选择。始终由用户选择。

   **在批量校验之前，为所选根目录一次性加载当前归档输入：**

   从该根目录中选一个已选变更，运行
   \`openspec-cn instructions archive --change "<selected-change>" --json\`，并带上
   相同的已选根目录标志。该查询是建议性且可选的：它只是提供
   额外的提示输入，因此绝不能阻塞批量操作。若它失败或返回
   无效 JSON —— 例如在尚不支持此命令的旧版 CLI 上
   —— 则在没有 context 与 operation guidance 的情况下继续批量操作。不要
   报告错误，也不要停止。

   有效的响应可能省略 \`context\` 与 \`operationGuidance\`。将
   \`context\` 视为整个批次的必需提示级输入：阅读并考虑
   它，并应用相关的项目事实、约定与约束。将
   \`operationGuidance\` 视为可选的增量建议：阅读并考虑每一条目，遵循那些适用且与内置批次工作流兼容的条目。

   将这两个字段与冲突分析、用户的显式选择、已解析路径、CLI 检查和命令契约分开对待。若 context 与其中某个控制输入冲突，报告冲突并保留控制值。若 guidance 不适用或与某个控制输入冲突，不要遵循它并解释原因。不要从任何字段推断跳过的提示、替换路径或标志，也不将它们的文本逐字复制到 specs、changes、archive 目录或输出摘要中。这些是提示级行为契约，不是可强制执行的检查。

3. **批量校验 - 收集所有所选变更的状态**

   对每个所选变更，收集：

   a. **产出物状态** - 运行 \`openspec-cn status --change "<name>" --json\`
      - 解析 \`schemaName\`、\`artifacts\`、\`planningHome\`、\`changeRoot\`、\`artifactPaths\` 和 \`actionContext\`
      - 记录哪些产出物为 \`done\`，哪些为其他状态

   b. **任务完成情况** - 从状态 JSON 读取 \`artifactPaths.tasks.existingOutputPaths\`
      - 统计 \`- [ ]\`（未完成）与 \`- [x]\`（已完成）
      - 若无任务文件，记为"无任务"

   c. **Delta specs** - 从状态 JSON 检查 \`artifactPaths.specs.existingOutputPaths\`
      - 列出存在哪些 capability spec
      - 对每个，提取需求名称（匹配 \`### Requirement: <name>\` 的行）
      - 将此列表作为唯一的增量 spec 来源。若 \`specs\` 条目
        缺失或列表为空，对该变更不执行 spec 同步或 specs-instruction 查找；不要从无关制品推断增量 spec。
      - 对每个变更独立评估，包括某些 schema 没有 \`specs\` 制品的混合 schema 批次。当某个变更没有增量 spec 或其 schema 不含 specs 时，对该变更继续而不进行 spec 同步（与单个变更跳过相同）。
4. **检测 spec 冲突**

   构建一个以 \`<capability-path>\`（相对于 \`specs/\` 的确切路径）为键的映射：

   \`\`\`text
   identity/user-auth -> [change-a, change-b]  <- 冲突（2 个及以上变更）
   billing/user-auth  -> [change-c]            <- 正常（完整路径不同）
   \`\`\`

   当 2 个及以上所选变更对同一个 \`<capability-path>\` 拥有 delta specs 时，即存在冲突。

5. **主动解决冲突**

   **对每个冲突**，调查代码库：

   a. **阅读 delta specs** - 从每个冲突变更中理解其声称新增/修改的内容

   b. **搜索代码库** 寻找实现证据：
      - 查找实现各 delta spec 中需求的代码
      - 检查相关文件、函数或测试

   c. **确定解决方案**：
      - 若仅一个变更实际已实现 -> 仅同步该变更的 specs
      - 若两者都已实现 -> 按时间顺序应用（先旧后新，新者覆盖）
      - 若两者都未实现 -> 跳过 spec 同步，警告用户

   d. **记录每个冲突的解决方案**：
      - 对每个增量 spec 的包含或排除决策，按变更和 \`<capability-path>\` 索引
      - 要应用哪些包含的增量 spec 以及按什么顺序
      - 哪些增量 spec 因实现缺失而从同步中排除
      - 理由（在代码库中发现了什么）

6. **展示汇总状态表**

   展示一个汇总所有变更的表格：

   \`\`\`markdown
   | 变更               | 产出物 | 任务 | Specs   | 冲突      | 状态   |
   |---------------------|-----------|-------|---------|-----------|--------|
   | schema-management   | 完成      | 5/5   | 2 delta | 无        | 就绪   |
   | project-config      | 完成      | 3/3   | 1 delta | 无        | 就绪   |
   | add-oauth           | 完成      | 4/4   | 1 delta | identity/user-auth (!) | 就绪*  |
   | add-verify-skill    | 剩余 1    | 2/5   | 无      | 无        | 警告   |
   \`\`\`

   对冲突，展示解决方案：
   \`\`\`text
   * 冲突解决：
     - identity/user-auth spec：将先应用 add-oauth 再应用 add-jwt（两者都已实现，按时间顺序）
   \`\`\`

   对未完成的变更，展示警告：
   \`\`\`text
   警告：
   - add-verify-skill：1 个未完成产出物，3 个未完成任务
   \`\`\`

7. **确认批量操作**

   询问用户单个确认问题：

   - "归档 N 个变更？" 选项依据状态而定
   - 选项可能包括：
     - "归档全部 N 个变更"
     - "仅归档 N 个就绪变更（跳过未完成）"
     - "取消"

   若存在未完成变更，明确说明它们将带警告归档。

   根据用户回答的意图路由，而不是精确匹配标签 —— 标签是你自己写的，
   所以匹配用户选择的选项，而非上面的措辞：
   - "取消" — 停止，不归档。报告未归档任何变更并跳过其余步骤。
   - "归档全部"选项 — 对每个已选变更继续
   - "仅就绪"选项 — 只继续步骤 6 表格中标记为 \`就绪\` 或 \`就绪*\` 的变更，其余在步骤 8d 中记为"跳过"。若某个 \`就绪*\` 变更的冲突对象被跳过，则仅基于将要归档的变更重新推导该冲突的解决方案。
   - 其他任何回答 — 再次询问，而不是归档

   在步骤 8 写入第一个主 spec 或移动任何变更之前，为已确认的批次获取所有需要的 specs 规则快照。对每个将要同步具体 \`artifactPaths.specs.existingOutputPaths\` 的变更，用相同的已选根目录标志运行 \`openspec-cn instructions specs --change "<name>" --json\` 恰好一次。在第一次写入或移动之前获取所有快照。若任何查询以非零状态退出或返回无效的制品指令 JSON，找出受影响的变更，报告错误，并在任何主 spec 写入或变更移动之前停止整个批次。不要把查询失败当作省略了规则。没有 \`rules\` 的有效响应就是无规则情况。

8. **为每个确认的变更执行归档**

   在处理之前，把步骤 5（以及步骤 7 中任何重新推导之后）记录的决策带入两个按 delta 划分的集合：
   - \`includedDeltas\`：来自已确认变更中所有无冲突的增量 spec，以及为解决冲突而选入同步的增量 spec
   - \`excludedDeltas\`：来自已确认变更中因实现缺失而被排除的冲突增量 spec
   - 单个变更可以同时拥有包含和排除的增量 spec。保持按 delta 决策，不要合并为按变更的同步标志。

   按确定的顺序处理各变更（遵循冲突解决方案）：

   a. **同步包含的增量 spec**：
      - 仅为有条目在 \`includedDeltas\` 中的变更内联运行 \`openspec-sync-specs\` 工作流（智能驱动合并），仅传递包含的 delta 路径，并明确指示忽略该变更的 \`excludedDeltas\`。等待其完成。
      - 对冲突，按已解析的顺序应用。
      - 把该变更已获取的 specs 规则快照传入内联同步；内联同步必须复用它，不要再次获取指令
      - 制品规则仅应用于该变更生成的主 spec。它们不改变冲突解决方案、归档行为或 CLI 契约，其文本也不会被复制到输出文件中
      - 不要委托给后台任务 —— 步骤 8c 会把 \`changeRoot\` 从一个仍在读取它的同步下方移走。
      - 若某个变更没有包含的增量 spec，不要为它运行同步工作流。

   b. **在移动 changeRoot 之前验证包含的增量 spec**：
      - 仅针对 \`includedDeltas\` 中的增量 spec，与 \`<planningHome.root>/openspec/specs/<capability-path>/spec.md\` 处的主 spec 重新运行比较（使用步骤 3 状态 JSON 中感知 store 的 \`planningHome.root\`，而不是硬编码的仓库路径）。
      - 验证主 specs 已更新：
        - ADDED 需求存在
        - MODIFIED 需求携带 delta 中指明的场景与描述更改，且其其他场景保持完好
        - REMOVED 需求已消失 —— 若此次同步退役了某个能力（移除了它的最后一条需求，使 \`## Requirements\` 为空），其主 spec 应被删除而不是留空；同步有意保留并报告过的 spec 也算匹配
        - RENAMED 需求以新名称存在且旧名称下已消失
      - 不要验证 \`excludedDeltas\` 中的增量 spec；它们被有意保留为未同步。
      - 若同步失败或任何能力未通过验证，报告差异并使该变更的 \`changeRoot\` 移动失败/跳过 —— 不要归档该变更。\`changeRoot\` 保持完好。

   c. **执行归档**：

      目标名称：若变更名已以 \`YYYY-MM-DD-\` 前缀开头则保持原样；否则将当前日期前置为 \`YYYY-MM-DD-<name>\`（与 \`openspec-cn archive\` 相同的规则）。

      \`\`\`bash
      mkdir -p "<planningHome.changesDir>/archive"
      mv "<changeRoot>" "<planningHome.changesDir>/archive/<target-name>"
      \`\`\`

   d. **记录每个变更的结果**：
      - 成功：归档成功
      - 失败：归档或 spec 验证期间出错（记录错误）
      - 跳过：用户选择不归档（如适用）
      - 同步跳过：对 \`excludedDeltas\` 中的每个增量，报告 \`sync skipped\` 并附上变更、\`<capability-path>\` 和记录的原因。这与跳过归档不同。

9. **展示汇总**

   展示最终结果：

   \`\`\`markdown
   ## 批量归档完成

   已归档 3 个变更：
   - schema-management-cli -> archive/2026-01-19-schema-management-cli/
   - project-config -> archive/2026-01-19-project-config/
   - add-oauth -> archive/2026-01-19-add-oauth/

   跳过 1 个变更：
   - add-verify-skill（用户选择不归档未完成项）

   Spec 同步汇总：
   - 4 个增量 spec 已同步到主 specs
   - 1 个增量 spec 同步已跳过（add-jwt，identity/user-auth：未找到实现）
   - 1 个冲突已解决（identity/user-auth：已同步 add-oauth，已跳过 add-jwt）
   \`\`\`

   若有失败：
   \`\`\`text
   失败 1 个变更：
   - some-change：归档目录已存在
   \`\`\`

**冲突解决示例**

示例 1：仅一个已实现
\`\`\`text
冲突：<planningHome.root>/openspec/specs/auth/spec.md 被以下变更触及：[add-oauth, add-jwt]

检查 add-oauth：
- Delta 新增 "OAuth Provider Integration" 需求
- 搜索代码库... 找到 src/auth/oauth.ts 实现了 OAuth 流程

检查 add-jwt：
- Delta 新增 "JWT Token Handling" 需求
- 搜索代码库... 未找到 JWT 实现

解决方案：仅 add-oauth 已实现。将仅同步 add-oauth specs。
\`\`\`

示例 2：两者都已实现
\`\`\`text
冲突：<planningHome.root>/openspec/specs/api/spec.md 被以下变更触及：[add-rest-api, add-graphql]

检查 add-rest-api（创建于 2026-01-10）：
- Delta 新增 "REST Endpoints" 需求
- 搜索代码库... 找到 src/api/rest.ts

检查 add-graphql（创建于 2026-01-15）：
- Delta 新增 "GraphQL Schema" 需求
- 搜索代码库... 找到 src/api/graphql.ts

解决方案：两者都已实现。将先应用 add-rest-api specs，
再应用 add-graphql specs（按时间顺序，新者优先）。
\`\`\`

**成功时输出**

\`\`\`markdown
## 批量归档完成

已归档 N 个变更：
- <change-1> -> archive/<target-name-1>/
- <change-2> -> archive/<target-name-2>/

Spec 同步汇总：
- N 个 delta spec 已同步到主 specs
- 无冲突（或：M 个冲突已解决）
\`\`\`

**部分成功时输出**

\`\`\`markdown
## 批量归档完成（部分）

已归档 N 个变更：
- <change-1> -> archive/<target-name-1>/

跳过 M 个变更：
- <change-2>（用户选择不归档未完成项）

失败 K 个变更：
- <change-3>：归档目录已存在
\`\`\`

**无变更时输出**

\`\`\`markdown
## 无可归档的变更

未找到活跃的变更。创建一个新变更即可开始。
\`\`\`

**护栏**
- 允许任意数量的变更（1+ 可以，2+ 是典型用例）
- 始终提示选择，绝不自动选择
- 尽早检测 spec 冲突，并通过检查代码库解决
- 当两个变更都已实现时，按时间顺序应用 specs
- 仅在实现缺失时跳过 spec 同步（警告用户）
- 确认前展示每个变更的清晰状态
- 对整个批次使用单次确认
- 用户取消确认后绝不归档 —— 被取消的批次不归档任何内容
- 跟踪并报告所有结果（成功/跳过/失败）
- 移动到归档时保留 .openspec.yaml
- 归档目录目标使用当前日期：YYYY-MM-DD-<name>；已以 \`YYYY-MM-DD-\` 前缀开头的名称保持原样（绝不叠加第二个日期）
- 若归档目标已存在，使该变更失败但继续处理其他变更
- 若请求同步，为每个包含增量 spec 的变更内联运行 \`openspec-sync-specs\` 工作流（agent 驱动）
- 将每个 delta 的 \`includedDeltas\` 和 \`excludedDeltas\` 决策带入执行；仅同步和验证包含的 delta
- 将每个被排除的增量报告为 \`sync skipped\`，但不把归档本身视为跳过
- 绝不在 spec 同步仍在进行时归档某个变更 —— 内联运行同步，并在移动 \`changeRoot\` 之前验证 \`<planningHome.root>/openspec/specs/<capability-path>/spec.md\` 处的主 specs
- 在 spec 检查或移动之前，为每个所选根目录一次性获取归档输入
- 在批次的第一次主 spec 写入或移动之前获取所有需要的 specs 规则快照
- 归档输入查询失败绝不阻塞批次；它会在没有 context 或 guidance 的情况下继续
- specs 指令查询失败会原子性地停止整个批次
- 没有具体 \`artifactPaths.specs.existingOutputPaths\` 的变更继续进行而不进行 spec 同步
- 跨批次应用相关的运行时 context 并报告冲突
- operation guidance 保持建议性质；考虑每一条目并解释被拒绝的建议
- 保持运行时输入、冲突分析、CLI 派生值和制品规则彼此分离
- 制品规则仅约束正在写入的 specs
- 绝不把运行时输入或制品规则文本原样复制到输出文件中`,
    license: 'MIT',
    compatibility: '需要 openspec-cn CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxBulkArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Bulk Archive',
    description: '一次性归档多个已完成的变更',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental', 'bulk'],
    content: `在单次操作中归档多个已完成的变更。

此技能允许您批量归档变更，通过检查代码库判断实际已实现的内容，从而智能处理 spec 冲突。

${STORE_SELECTION_GUIDANCE}

\`<capability-path>\` 是相对于 \`specs/\` 的 spec 目录（例如 \`user-auth\` 或 \`identity/user-auth\`）。在解析主 spec 时保留每个增量 spec 的完整路径。

**Input**: None required（通过提示选择）

**步骤**

1. **获取活跃变更**

   运行 \`openspec-cn list --json\` 获取所有活跃变更。

   若无活跃变更，告知用户并停止。

2. **提示选择变更**

   请用户选择变更（多选）：
   - 展示每个变更及其 schema
   - 包含"全部变更"选项
   - 允许任意数量的选择（1+ 可以，2+ 是典型用例）

   **重要提示**：切勿自动选择。始终由用户选择。

   **在批量校验之前，为所选根目录一次性加载当前归档输入：**

   从该根目录中选一个已选变更，运行
   \`openspec-cn instructions archive --change "<selected-change>" --json\`，并带上
   相同的已选根目录标志。该查询是建议性且可选的：它只是提供
   额外的提示输入，因此绝不能阻塞批量操作。若它失败或返回
   无效 JSON —— 例如在尚不支持此命令的旧版 CLI 上
   —— 则在没有 context 与 operation guidance 的情况下继续批量操作。不要
   报告错误，也不要停止。

   有效的响应可能省略 \`context\` 与 \`operationGuidance\`。将
   \`context\` 视为整个批次的必需提示级输入：阅读并考虑
   它，并应用相关的项目事实、约定与约束。将
   \`operationGuidance\` 视为可选的增量建议：阅读并考虑每一条目，遵循那些适用且与内置批次工作流兼容的条目。

   将这两个字段与冲突分析、用户的显式选择、已解析路径、CLI 检查和命令契约分开对待。若 context 与其中某个控制输入冲突，报告冲突并保留控制值。若 guidance 不适用或与某个控制输入冲突，不要遵循它并解释原因。不要从任何字段推断跳过的提示、替换路径或标志，也不将它们的文本逐字复制到 specs、changes、archive 目录或输出摘要中。这些是提示级行为契约，不是可强制执行的检查。

3. **批量校验 - 收集所有所选变更的状态**

   对每个所选变更，收集：

   a. **产出物状态** - 运行 \`openspec-cn status --change "<name>" --json\`
      - 解析 \`schemaName\`、\`artifacts\`、\`planningHome\`、\`changeRoot\`、\`artifactPaths\` 和 \`actionContext\`
      - 记录哪些产出物为 \`done\`，哪些为其他状态

   b. **任务完成情况** - 从状态 JSON 读取 \`artifactPaths.tasks.existingOutputPaths\`
      - 统计 \`- [ ]\`（未完成）与 \`- [x]\`（已完成）
      - 若无任务文件，记为"无任务"

   c. **Delta specs** - 从状态 JSON 检查 \`artifactPaths.specs.existingOutputPaths\`
      - 列出存在哪些 capability spec
      - 对每个，提取需求名称（匹配 \`### Requirement: <name>\` 的行）
      - 将此列表作为唯一的增量 spec 来源。若 \`specs\` 条目缺失或列表为空，对该变更不执行 spec 同步或 specs-instruction 查找；不要从无关制品推断增量 spec。
      - 对每个变更独立评估，包括某些 schema 没有 \`specs\` 制品的混合 schema 批次。

4. **检测 spec 冲突**

   构建一个以 \`<capability-path>\`（相对于 \`specs/\` 的确切路径）为键的映射：

   \`\`\`text
   identity/user-auth -> [change-a, change-b]  <- 冲突（2 个及以上变更）
   billing/user-auth  -> [change-c]            <- 正常（完整路径不同）
   \`\`\`

   当 2 个及以上所选变更对同一个 \`<capability-path>\` 拥有 delta specs 时，即存在冲突。

5. **主动解决冲突**

   **对每个冲突**，调查代码库：

   a. **阅读 delta specs** - 从每个冲突变更中理解其声称新增/修改的内容

   b. **搜索代码库** 寻找实现证据：
      - 查找实现各 delta spec 中需求的代码
      - 检查相关文件、函数或测试

   c. **确定解决方案**：
      - 若仅一个变更实际已实现 -> 仅同步该变更的 specs
      - 若两者都已实现 -> 按时间顺序应用（先旧后新，新者覆盖）
      - 若两者都未实现 -> 跳过 spec 同步，警告用户

   d. **记录每个冲突的解决方案**：
      - 对每个增量 spec 的包含或排除决策，按变更和 \`<capability-path>\` 索引
      - 要应用哪些包含的增量 spec 以及按什么顺序
      - 哪些增量 spec 因实现缺失而从同步中排除
      - 理由（在代码库中发现了什么）

6. **展示汇总状态表**

   展示一个汇总所有变更的表格：

   \`\`\`markdown
   | 变更               | 产出物 | 任务 | Specs   | 冲突      | 状态   |
   |---------------------|-----------|-------|---------|-----------|--------|
   | schema-management   | 完成      | 5/5   | 2 delta | 无        | 就绪   |
   | project-config      | 完成      | 3/3   | 1 delta | 无        | 就绪   |
   | add-oauth           | 完成      | 4/4   | 1 delta | identity/user-auth (!) | 就绪*  |
   | add-verify-skill    | 剩余 1    | 2/5   | 无      | 无        | 警告   |
   \`\`\`

   对冲突，展示解决方案：
   \`\`\`text
   * 冲突解决：
     - identity/user-auth spec：将先应用 add-oauth 再应用 add-jwt（两者都已实现，按时间顺序）
   \`\`\`

   对未完成的变更，展示警告：
   \`\`\`text
   警告：
   - add-verify-skill：1 个未完成产出物，3 个未完成任务
   \`\`\`

7. **确认批量操作**

   询问用户单个确认问题：

   - "归档 N 个变更？" 选项依据状态而定
   - 选项可能包括：
     - "归档全部 N 个变更"
     - "仅归档 N 个就绪变更（跳过未完成）"
     - "取消"

   若存在未完成变更，明确说明它们将带警告归档。

   根据用户回答的意图路由，而不是精确匹配标签 —— 标签是你自己写的，
   所以匹配用户选择的选项，而非上面的措辞：
   - "取消" — 停止，不归档。报告未归档任何变更并跳过其余步骤。
   - "归档全部"选项 — 对每个已选变更继续
   - "仅就绪"选项 — 只继续步骤 6 表格中标记为 \`就绪\` 或 \`就绪*\` 的变更，其余在步骤 8d 中记为"跳过"。若某个 \`就绪*\` 变更的冲突对象被跳过，则仅基于将要归档的变更重新推导该冲突的解决方案。
   - 其他任何回答 — 再次询问，而不是归档

   在步骤 8 写入第一个主 spec 或移动任何变更之前，为已确认的批次获取所有需要的 specs 规则快照。对每个将要同步具体 \`artifactPaths.specs.existingOutputPaths\` 的变更，用相同的已选根目录标志运行 \`openspec-cn instructions specs --change "<name>" --json\` 恰好一次。在第一次写入或移动之前获取所有快照。若任何查询以非零状态退出或返回无效的制品指令 JSON，找出受影响的变更，报告错误，并在任何主 spec 写入或变更移动之前停止整个批次。不要把查询失败当作省略了规则。没有 \`rules\` 的有效响应就是无规则情况。

8. **为每个确认的变更执行归档**

   在处理之前，把步骤 5（以及步骤 7 中任何重新推导之后）记录的决策带入两个按 delta 划分的集合：
   - \`includedDeltas\`：来自已确认变更中所有无冲突的增量 spec，以及为解决冲突而选入同步的增量 spec
   - \`excludedDeltas\`：来自已确认变更中因实现缺失而被排除的冲突增量 spec
   - 单个变更可以同时拥有包含和排除的增量 spec。保持按 delta 决策，不要合并为按变更的同步标志。

   按确定的顺序处理各变更（遵循冲突解决方案）：

   a. **同步包含的增量 spec**：
      - 仅为有条目在 \`includedDeltas\` 中的变更内联运行 \`/opsx:sync\` 工作流（智能驱动合并），仅传递包含的 delta 路径，并明确指示忽略该变更的 \`excludedDeltas\`。等待其完成。
      - 对冲突，按已解析的顺序应用。
      - 把该变更已获取的 specs 规则快照传入内联同步；内联同步必须复用它，不要再次获取指令
      - 制品规则仅应用于该变更生成的主 spec。它们不改变冲突解决方案、归档行为或 CLI 契约，其文本也不会被复制到输出文件中
      - 不要委托给后台任务 —— 步骤 8c 会把 \`changeRoot\` 从一个仍在读取它的同步下方移走。
      - 若某个变更没有包含的增量 spec，不要为它运行同步工作流。

   b. **在移动 changeRoot 之前验证包含的增量 spec**：
      - 仅针对 \`includedDeltas\` 中的增量 spec，与 \`<planningHome.root>/openspec/specs/<capability-path>/spec.md\` 处的主 spec 重新运行比较（使用步骤 3 状态 JSON 中感知 store 的 \`planningHome.root\`，而不是硬编码的仓库路径）。
      - 验证主 specs 已更新：
        - ADDED 需求存在
        - MODIFIED 需求携带 delta 中指明的场景与描述更改，且其其他场景保持完好
        - REMOVED 需求已消失 —— 若此次同步退役了某个能力（移除了它的最后一条需求，使 \`## Requirements\` 为空），其主 spec 应被删除而不是留空；同步有意保留并报告过的 spec 也算匹配
        - RENAMED 需求以新名称存在且旧名称下已消失
      - 不要验证 \`excludedDeltas\` 中的增量 spec；它们被有意保留为未同步。
      - 若同步失败或任何能力未通过验证，报告差异并使该变更的 \`changeRoot\` 移动失败/跳过 —— 不要归档该变更。\`changeRoot\` 保持完好。

   c. **执行归档**：

      目标名称：若变更名已以 \`YYYY-MM-DD-\` 前缀开头则保持原样；否则将当前日期前置为 \`YYYY-MM-DD-<name>\`（与 \`openspec-cn archive\` 相同的规则）。

      \`\`\`bash
      mkdir -p "<planningHome.changesDir>/archive"
      mv "<changeRoot>" "<planningHome.changesDir>/archive/<target-name>"
      \`\`\`

   d. **记录每个变更的结果**：
      - 成功：归档成功
      - 失败：归档或 spec 验证期间出错（记录错误）
      - 跳过：用户选择不归档（如适用）
      - 同步跳过：对 \`excludedDeltas\` 中的每个增量，报告 \`sync skipped\` 并附上变更、\`<capability-path>\` 和记录的原因。这与跳过归档不同。

9. **展示汇总**

   展示最终结果：

   \`\`\`markdown
   ## 批量归档完成

   已归档 3 个变更：
   - schema-management-cli -> archive/2026-01-19-schema-management-cli/
   - project-config -> archive/2026-01-19-project-config/
   - add-oauth -> archive/2026-01-19-add-oauth/

   跳过 1 个变更：
   - add-verify-skill（用户选择不归档未完成项）

   Spec 同步汇总：
   - 4 个增量 spec 已同步到主 specs
   - 1 个增量 spec 同步已跳过（add-jwt，identity/user-auth：未找到实现）
   - 1 个冲突已解决（identity/user-auth：已同步 add-oauth，已跳过 add-jwt）
   \`\`\`

   若有失败：
   \`\`\`text
   失败 1 个变更：
   - some-change：归档目录已存在
   \`\`\`

**冲突解决示例**

示例 1：仅一个已实现
\`\`\`text
冲突：<planningHome.root>/openspec/specs/auth/spec.md 被以下变更触及：[add-oauth, add-jwt]

检查 add-oauth：
- Delta 新增 "OAuth Provider Integration" 需求
- 搜索代码库... 找到 src/auth/oauth.ts 实现了 OAuth 流程

检查 add-jwt：
- Delta 新增 "JWT Token Handling" 需求
- 搜索代码库... 未找到 JWT 实现

解决方案：仅 add-oauth 已实现。将仅同步 add-oauth specs。
\`\`\`

示例 2：两者都已实现
\`\`\`text
冲突：<planningHome.root>/openspec/specs/api/spec.md 被以下变更触及：[add-rest-api, add-graphql]

检查 add-rest-api（创建于 2026-01-10）：
- Delta 新增 "REST Endpoints" 需求
- 搜索代码库... 找到 src/api/rest.ts

检查 add-graphql（创建于 2026-01-15）：
- Delta 新增 "GraphQL Schema" 需求
- 搜索代码库... 找到 src/api/graphql.ts

解决方案：两者都已实现。将先应用 add-rest-api specs，
再应用 add-graphql specs（按时间顺序，新者优先）。
\`\`\`

**成功时输出**

\`\`\`markdown
## 批量归档完成

已归档 N 个变更：
- <change-1> -> archive/<target-name-1>/
- <change-2> -> archive/<target-name-2>/

Spec 同步汇总：
- N 个 delta spec 已同步到主 specs
- 无冲突（或：M 个冲突已解决）
\`\`\`

**部分成功时输出**

\`\`\`markdown
## 批量归档完成（部分）

已归档 N 个变更：
- <change-1> -> archive/<target-name-1>/

跳过 M 个变更：
- <change-2>（用户选择不归档未完成项）

失败 K 个变更：
- <change-3>：归档目录已存在
\`\`\`

**无变更时输出**

\`\`\`markdown
## 无可归档的变更

未找到活跃的变更。创建一个新变更即可开始。
\`\`\`

**护栏**
- 允许任意数量的变更（1+ 可以，2+ 是典型用例）
- 始终提示选择，绝不自动选择
- 尽早检测 spec 冲突，并通过检查代码库解决
- 当两个变更都已实现时，按时间顺序应用 specs
- 仅在实现缺失时跳过 spec 同步（警告用户）
- 确认前展示每个变更的清晰状态
- 对整个批次使用单次确认
- 用户取消确认后绝不归档 —— 被取消的批次不归档任何内容
- 跟踪并报告所有结果（成功/跳过/失败）
- 移动到归档时保留 .openspec.yaml
- 归档目录目标使用当前日期：YYYY-MM-DD-<name>；已以 \`YYYY-MM-DD-\` 前缀开头的名称保持原样（绝不叠加第二个日期）
- 若归档目标已存在，使该变更失败但继续处理其他变更
- 若请求同步，为每个包含增量 spec 的变更内联运行 \`/opsx:sync\` 工作流（agent 驱动）
- 将每个 delta 的 \`includedDeltas\` 和 \`excludedDeltas\` 决策带入执行；仅同步和验证包含的 delta
- 将每个被排除的增量报告为 \`sync skipped\`，但不把归档本身视为跳过
- 绝不在 spec 同步仍在进行时归档某个变更 —— 内联运行同步，并在移动 \`changeRoot\` 之前验证 \`<planningHome.root>/openspec/specs/<capability-path>/spec.md\` 处的主 specs
- 在 spec 检查或移动之前，为每个所选根目录一次性获取归档输入
- 在批次的第一次主 spec 写入或移动之前获取所有需要的 specs 规则快照
- 归档输入查询失败绝不阻塞批次；它会在没有 context 或 guidance 的情况下继续
- specs 指令查询失败会原子性地停止整个批次
- 没有具体 \`artifactPaths.specs.existingOutputPaths\` 的变更继续进行而不进行 spec 同步
- 跨批次应用相关的运行时 context 并报告冲突
- operation guidance 保持建议性质；考虑每一条目并解释被拒绝的建议
- 保持运行时输入、冲突分析、CLI 派生值和制品规则彼此分离
- 制品规则仅约束正在写入的 specs
- 绝不把运行时输入或制品规则文本原样复制到输出文件中`
  };
}
