/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate } from '../types.js';

export function getFeedbackSkillTemplate(): SkillTemplate {
  return {
    name: 'feedback',
    description: '收集并提交关于 OpenSpec 的用户反馈，包含上下文丰富和匿名化处理。',
    instructions: `帮助用户提交关于 OpenSpec 的反馈。

**目标**：引导用户完成反馈的收集、丰富和提交，同时通过匿名化确保隐私。

**流程**

1. **从对话中收集上下文**
   - 回顾最近的对话历史以获取上下文
   - 识别正在执行什么任务
   - 注意哪些方面做得好或不好
   - 捕获具体的摩擦点或赞扬

2. **起草丰富的反馈**
   - 创建清晰、描述性的标题（单句，无需 "Feedback:" 前缀）
   - 编写正文，包括：
     - 用户想做什么
     - 发生了什么（好或坏）
     - 对话中的相关上下文
     - 任何具体建议或请求

3. **匿名化敏感信息**
   - 将文件路径替换为 \`<path>\` 或通用描述
   - 将 API 密钥、令牌、机密替换为 \`<redacted>\`
   - 将公司/组织名替换为 \`<company>\`
   - 将个人姓名替换为 \`<user>\`
   - 将具体 URL 替换为 \`<url>\`，除非是公开/相关的
   - 保留有助于理解问题的技术细节

4. **展示草稿以获批准**
   - 向用户展示完整草稿
   - 清晰显示标题和正文
   - 提交前请求明确批准
   - 允许用户请求修改

5. **确认后提交**
   - 使用 \`openspec-cn feedback\` 命令提交
   - 格式：\`openspec-cn feedback "title" --body "body content"\`
   - 命令会在 Issue 正文中保留标题文本，并缩短过长的 GitHub Issue 标题
   - 命令会自动添加元数据（版本、平台、时间戳）

**草稿示例**

\`\`\`
标题：产出物工作流中的错误处理需要改进

正文：
我正在创建新变更时遇到了产出物工作流的问题。当我创建
proposal 后尝试继续时，系统没有明确指示我需要先完成
specs。

建议：添加更清晰的错误消息，解释产出物工作流中的
依赖链。例如 "无法创建 design.md，因为 specs 未完成
（0/2 完成）。"

上下文：在 spec-driven schema 中使用 <path>/my-project
\`\`\`

**匿名化示例**

之前：
\`\`\`
处理 /Users/john/mycompany/auth-service/src/oauth.ts
失败，API 密钥：sk_live_abc123xyz
在 Acme Corp 工作
\`\`\`

之后：
\`\`\`
处理 <path>/oauth.ts
失败，API 密钥：<redacted>
在 <company> 工作
\`\`\`

**护栏**

- 必须在提交前展示完整草稿
- 必须请求明确批准
- 必须匿名化敏感信息
- 允许用户在提交前修改草稿
- 不要在用户未确认的情况下提交
- 要包含相关技术上下文
- 要保留对话特定的洞察

**需要用户确认**

始终询问：
\`\`\`
这是我起草的反馈：

标题：[title]

正文：
[body]

这样看起来可以吗？我可以修改，或者直接提交。
\`\`\`

仅在用户确认后继续提交。`,
    license: 'MIT',
    compatibility: '需要 openspec-cn CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}
