/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getFfChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-ff-change',
    description: '快速推进 OpenSpec 产出物创建。当用户想快速创建实现所需的所有产出物而无需逐个处理时使用。',
    instructions: `快速推进产出物创建 - 一次性生成开始实现所需的所有内容。

${STORE_SELECTION_GUIDANCE}

**Input**: 用户的请求应当包含变更名（kebab-case）或对想要构建内容的描述。

**步骤**

1. **如果没有提供明确的输入，询问他们想要构建什么**

   询问用户（开放式，不设预设选项）：
   > "你想做什么变更？描述一下你想构建或修复的内容。"

   根据他们的描述，推导出一个 kebab-case 名称（例如："add user authentication" → \`add-user-auth\`）。

   **重要提示**：在不了解用户想要构建什么的情况下，请勿继续。

2. **创建变更目录**
   \`\`\`bash
   openspec-cn new change "<name>"
   \`\`\`
   这将在 CLI 解析的规划主目录中创建一个脚手架变更。

3. **获取产出物构建顺序**
   \`\`\`bash
   openspec-cn status --change "<name>" --json
   \`\`\`
   解析 JSON 以获取：
   - \`applyRequires\`：实现前所需的产出物 ID 数组（例如 \`["tasks"]\`）
   - \`artifacts\`：所有产出物列表，每个包含其 \`status\` 和 \`requires\` 边（它直接依赖的产出物 ID）
   - \`planningHome\`、\`changeRoot\`、\`artifactPaths\` 和 \`actionContext\`：路径和作用域上下文。请使用这些值而非假设仓库本地路径。

4. **创建所需集合中的每个产出物**

   使用待办清单跟踪产出物进度。

   按依赖顺序循环遍历产出物（没有待处理依赖项的产出物优先）：

   a. **对于每个 \`ready\`（依赖项已满足）的产出物**：
      - 获取指令：
        \`\`\`bash
        openspec-cn instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - 指令 JSON 包含：
        - \`context\`：项目背景（给你的约束 - 不要包含在输出中）
        - \`rules\`：产出物特定规则（给你的约束 - 不要包含在输出中）
        - \`template\`：输出文件使用的结构
        - \`instruction\`：此产出物类型的 schema 特定指导
        - \`skipped\`/\`warning\`：当变更声明 skip_specs 且此产出物必须不创建时出现 - 停止并选择另一个产出物
        - \`resolvedOutputPath\`：写入产出物的已解析路径或模式
        - \`dependencies\`：已完成的需要读取以获取上下文的产出物
      - 读取所有已完成的依赖文件以获取上下文 - 始终从磁盘重新读取，即使在对话中之前已看到（用户可能已编辑过）
      - 若 \`instruction\` 字段将创建委托给特定 skill 或命令，则调用它来生成产出物，而不是自己写入文件，然后验证产出物文件是否存在于 \`resolvedOutputPath\`
      - 否则，使用 \`template\` 作为结构创建产出物文件，并写入 \`resolvedOutputPath\`。若 \`resolvedOutputPath\` 是一个 glob，遵循 \`instruction\` 选择具体文件路径
      - 将 \`context\` 和 \`rules\` 作为约束应用 - 但不要将它们复制到文件中
      - 显示简要进度："已创建 <artifact-id>"

   b. **持续创建直到所需集合中的每个产出物都存在（不仅仅是 \`apply.requires\`）**
      - 创建每个产出物后，重新运行 \`openspec-cn status --change "<name>" --json\`
      - 所需集合是 \`applyRequires\` 加上通过跟踪 \`status --json\` 中的 \`requires\` 边从这些产出物可达的每个产出物 - 传递地遍历它们（spec-driven 涵盖 proposal、specs、design、tasks）。不要触碰此集合之外的产出物
      - \`status\` 仅基于文件存在性，因此一个显示 \`done\` 的 \`applyRequires\` 产出物并不意味着其依赖项存在 - 过早写入 \`tasks.md\` 会标记 \`tasks\` 为 done，但 \`specs\` 从未写入。使用每个产出物的 \`requires\` 边而非其 \`status\` 来构建所需集合：一个 \`done\` 产出物仍然列出其依赖项
      - 已显示 \`status: "skipped"\` 的产出物即已满足：变更在 \`.openspec.yaml\` 中声明了 \`skip_specs\`，因此其文件必须不存在。永远不要尝试创建它
      - 创建所需集合中缺失的每个产出物，然后重新检查 - 创建一个可能会解锁其他产出物
      - 仅当 \`status\` 已报告为 \`skipped\`，或其自身 \`instruction\` 表明是条件性的时才跳过：运行 \`openspec-cn instructions <artifact-id> --change "<name>" --json\`，仅当其 \`instruction\` 字段标记为可选时才跳过（例如 "create only if..."）。spec-driven 的 \`design.md\` 符合此条件；\`specs\` 仅通过上述 \`skipped\` 状态符合，绝不能凭你的判断。告知用户，且不要重新考虑
      - 依赖项是使能因素而非关卡：若一个必需产出物仍 \`blocked\` 仅因为你跳过了条件性依赖项，照样写入
      - 当所需集合中的每个产出物为 \`done\`、\`skipped\` 或已被有意跳过时停止

   c. **若某个产出物需要用户输入**（上下文不清）：
      - 请求用户澄清
      - 然后继续创建

5. **显示最终状态**
   \`\`\`bash
   openspec-cn status --change "<name>"
   \`\`\`

**输出**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions, plus any conditional artifact you skipped and why
- What's ready: "All artifacts needed for implementation are ready."
- Prompt: "Run \`/opsx:apply\` or ask me to implement to start working on the tasks."

**产出物创建指南**

- 遵循来自 \`openspec-cn instructions\` 每个制品类型输出中的 \`instruction\` 字段 — 它是权威指导，即使产出物名称熟悉
- 若 \`instruction\` 字段指示你使用特定 skill 或命令创建产出物，则调用它而非直接写入产出物
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output

**Guardrails**
- Create every artifact the apply phase transitively depends on, not just the ids listed in \`apply.requires\`
- Always read dependency artifacts before creating a new one - re-read from disk, not from conversation memory (files may have changed since you last saw them)
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, suggest continuing that change instead
- Verify each artifact file exists after writing before proceeding to next`,
    license: 'MIT',
    compatibility: '需要 openspec-cn CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxFfCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Fast Forward',
    description: '创建变更并一次性生成实现所需的所有产出物',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `快速推进产出物创建 - 一次性生成开始实现所需的所有内容。

${STORE_SELECTION_GUIDANCE}

**Input**: \`/opsx:ff\` 之后的参数是变更名（kebab-case），或用户想要构建内容的描述。

**步骤**

1. **如果没有提供输入，询问他们想要构建什么**

   询问用户（开放式，不设预设选项）：
   > "你想做什么变更？描述一下你想构建或修复的内容。"

   根据他们的描述，推导出一个 kebab-case 名称（例如："add user authentication" → \`add-user-auth\`）。

   **重要提示**：在不了解用户想要构建什么的情况下，请勿继续。

2. **创建变更目录**
   \`\`\`bash
   openspec-cn new change "<name>"
   \`\`\`
   这将在 CLI 解析的规划主目录中创建一个脚手架变更。

3. **获取产出物构建顺序**
   \`\`\`bash
   openspec-cn status --change "<name>" --json
   \`\`\`
   解析 JSON 以获取：
   - \`applyRequires\`：实现前所需的产出物 ID 数组（例如 \`["tasks"]\`）
   - \`artifacts\`：所有产出物列表，每个包含其 \`status\` 和 \`requires\` 边（它直接依赖的产出物 ID）
   - \`planningHome\`、\`changeRoot\`、\`artifactPaths\` 和 \`actionContext\`：路径和作用域上下文。请使用这些值而非假设仓库本地路径。

4. **创建所需集合中的每个产出物**

   使用待办清单跟踪产出物进度。

   按依赖顺序循环遍历产出物（没有待处理依赖项的产出物优先）：

   a. **对于每个 \`ready\`（依赖项已满足）的产出物**：
      - 获取指令：
        \`\`\`bash
        openspec-cn instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - 指令 JSON 包含：
        - \`context\`：项目背景（给你的约束 - 不要包含在输出中）
        - \`rules\`：产出物特定规则（给你的约束 - 不要包含在输出中）
        - \`template\`：输出文件使用的结构
        - \`instruction\`：此产出物类型的 schema 特定指导
        - \`skipped\`/\`warning\`：当变更声明 skip_specs 且此产出物必须不创建时出现 - 停止并选择另一个产出物
        - \`resolvedOutputPath\`：写入产出物的已解析路径或模式
        - \`dependencies\`：已完成的需要读取以获取上下文的产出物
      - 读取所有已完成的依赖文件以获取上下文 - 始终从磁盘重新读取，即使在对话中之前已看到（用户可能已编辑过）
      - 若 \`instruction\` 字段将创建委托给特定 skill 或命令，则调用它来生成产出物，而不是自己写入文件，然后验证产出物文件是否存在于 \`resolvedOutputPath\`
      - 否则，使用 \`template\` 作为结构创建产出物文件，并写入 \`resolvedOutputPath\`。若 \`resolvedOutputPath\` 是一个 glob，遵循 \`instruction\` 选择具体文件路径
      - 将 \`context\` 和 \`rules\` 作为约束应用 - 但不要将它们复制到文件中
      - 显示简要进度："已创建 <artifact-id>"

   b. **持续创建直到所需集合中的每个产出物都存在（不仅仅是 \`apply.requires\`）**
      - 创建每个产出物后，重新运行 \`openspec-cn status --change "<name>" --json\`
      - 所需集合是 \`applyRequires\` 加上通过跟踪 \`status --json\` 中的 \`requires\` 边从这些产出物可达的每个产出物 - 传递地遍历它们（spec-driven 涵盖 proposal、specs、design、tasks）。不要触碰此集合之外的产出物
      - \`status\` 仅基于文件存在性，因此一个显示 \`done\` 的 \`applyRequires\` 产出物并不意味着其依赖项存在 - 过早写入 \`tasks.md\` 会标记 \`tasks\` 为 done，但 \`specs\` 从未写入。使用每个产出物的 \`requires\` 边而非其 \`status\` 来构建所需集合：一个 \`done\` 产出物仍然列出其依赖项
      - 已显示 \`status: "skipped"\` 的产出物即已满足：变更在 \`.openspec.yaml\` 中声明了 \`skip_specs\`，因此其文件必须不存在。永远不要尝试创建它
      - 创建所需集合中缺失的每个产出物，然后重新检查 - 创建一个可能会解锁其他产出物
      - 仅当 \`status\` 已报告为 \`skipped\`，或其自身 \`instruction\` 表明是条件性的时才跳过：运行 \`openspec-cn instructions <artifact-id> --change "<name>" --json\`，仅当其 \`instruction\` 字段标记为可选时才跳过（例如 "create only if..."）。spec-driven 的 \`design.md\` 符合此条件；\`specs\` 仅通过上述 \`skipped\` 状态符合，绝不能凭你的判断。告知用户，且不要重新考虑
      - 依赖项是使能因素而非关卡：若一个必需产出物仍 \`blocked\` 仅因为你跳过了条件性依赖项，照样写入
      - 当所需集合中的每个产出物为 \`done\`、\`skipped\` 或已被有意跳过时停止

   c. **若某个产出物需要用户输入**（上下文不清）：
      - 请求用户澄清
      - 然后继续创建

5. **显示最终状态**
   \`\`\`bash
   openspec-cn status --change "<name>"
   \`\`\`

**输出**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions, plus any conditional artifact you skipped and why
- What's ready: "All artifacts needed for implementation are ready."
- Prompt: "Run \`/opsx:apply\` to start implementing."

**产出物创建指南**

- 遵循来自 \`openspec-cn instructions\` 每个制品类型输出中的 \`instruction\` 字段 — 它是权威指导，即使产出物名称熟悉
- 若 \`instruction\` 字段指示你使用特定 skill 或命令创建产出物，则调用它而非直接写入产出物
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output

**Guardrails**
- Create every artifact the apply phase transitively depends on, not just the ids listed in \`apply.requires\`
- Always read dependency artifacts before creating a new one - re-read from disk, not from conversation memory (files may have changed since you last saw them)
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- Verify each artifact file exists after writing before proceeding to next`
  };
}
