/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { optionalWorkflow } from '../optional-workflow.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';
import { PROJECT_ROOT_GUARD } from './project-root.js';

/**
 * Passages that hand off to `/opsx:continue` or `/opsx:new`. Neither workflow
 * is in the `core` profile, so each is authored with a CLI fallback and
 * resolved at generation time (see optional-workflow.ts). Shared by both
 * surfaces below so the skill and the command cannot drift apart.
 */
const CONTINUE_SCOPE_NOTE = optionalWorkflow(
  'continue',
  '本工作流仅修订已存在的制品；`/opsx:continue` 负责创建不存在的制品。',
  '本工作流仅修订已存在的制品；它绝不创建缺失的制品。制品缺失时，`openspec-cn status --change "<name>" --json` 指出下一个制品，`openspec-cn instructions "<artifact-id>" --change "<name>" --json` 解释如何撰写它。'
);

const CONTINUE_CREATE_THEM = optionalWorkflow(
  'continue',
  '引导用户使用 `/opsx:continue` 来创建它们',
  '引导用户使用 `openspec-cn instructions "<artifact-id>" --change "<name>" --json` 来创建它们'
);

const CONTINUE_NEXT_STEP = optionalWorkflow(
  'continue',
  '建议 `/opsx:continue` 创建它们',
  '运行 `openspec-cn status --change "<name>" --json` 获取下一个制品，并引导用户使用 `openspec-cn instructions "<artifact-id>" --change "<name>" --json` 来创建它'
);

const CONTINUE_DEFERRED = optionalWorkflow(
  'continue',
  '推迟到 `/opsx:continue` 的任何内容（尚无文件的制品且状态为 `ready` 或 `blocked`，绝不包括 `skipped` 制品）',
  '因尚不存在而推迟的任何内容（尚无文件的制品且状态为 `ready` 或 `blocked`，绝不包括 `skipped` 制品）'
);

const CONTINUE_FRONTIER = optionalWorkflow(
  'continue',
  '那是 `/opsx:continue` 的职责',
  '创建它们是本工作流之外的独立步骤'
);

/**
 * `apply` and `archive` are in the `core` profile but not guaranteed in a
 * custom one, so their handoffs are resolved the same way.
 */
const APPLY_DELTA_HANDOFF = optionalWorkflow(
  'apply',
  '建议 `/opsx:apply` 将增量带入代码',
  '说明代码可能需要更新，并提议将增量带入其中'
);

const APPLY_GUARDRAIL = optionalWorkflow(
  'apply',
  '停止并指向 `/opsx:apply`',
  '停止并说明修订后的计划现在暗示代码更改；实现它们是本工作流之外的独立步骤'
);

const ARCHIVE_HANDOFF = optionalWorkflow(
  'archive',
  '建议 `/opsx:archive`',
  '建议用 `openspec-cn archive "<name>"` 归档'
);

const INTENT_CHANGE_GUARDRAIL = optionalWorkflow(
  'new',
  '建议用 `/opsx:new` 重新开始（"更新 vs 重新开始" 启发式）',
  '请求一个不同的未使用变更名称，并建议改用 `openspec-cn new change "<new-change-name>"`（"更新 vs 重新开始" 启发式）'
);

export function getUpdateChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-update-change',
    description: "修订 OpenSpec 变更的现有规划制品并保持它们之间的一致。当用户想修订变更的计划、将新决定纳入其中，或在编辑后调和其制品时使用。也在用户说 \"openspec update change\" 或 \"opsx update\" 时使用。若用户指的是 openspec update CLI 命令（刷新生成的文件），请改为运行该命令。绝不要编辑代码。",
    instructions: `修订变更的现有规划制品并保持它们之间一致。绝不要编辑代码。

${STORE_SELECTION_GUIDANCE}

${PROJECT_ROOT_GUARD}

**Input**: 可选地指定变更名称。若省略，检查能否从对话上下文推断。若模糊或歧义，你必须提示用户从可用变更中选择。

${CONTINUE_SCOPE_NOTE}

**步骤**

1. **选择变更**

   若提供了名称，使用它。否则：
   - 从对话上下文推断（若用户提到了某个变更）
   - 若仅有一个活跃变更则自动选择
   - 若存在歧义，运行 \`openspec-cn list --json\` 获取按最近修改排序的可用变更，并让用户选择

   提示时，展示最近修改的前 3-4 个变更作为选项，显示：
   - 变更名称
   - 状态（例如 "0/5 tasks"、"complete"、"no tasks"）
   - 最近修改时间（来自 \`lastModified\` 字段）

   将最近修改的变更标记为 "(推荐)"，因为这很可能是用户想更新的。

   始终宣告："使用变更：<name>"，以及如何覆盖（例如 \`/opsx:update <other>\`）。

2. **获取变更的制品**
   \`\`\`bash
   openspec-cn status --change "<name>" --json
   \`\`\`
   解析 JSON 以理解当前状态。响应包括：
   - \`schemaName\`：使用的工作流 schema（例如 "spec-driven"）
   - \`artifacts\`：制品数组及其状态（"done"、"skipped"、"ready"、"blocked"）
   - \`isPlanningComplete\`：布尔值，表示所有规划制品是否已完成。较旧 CLI 版本以 \`isComplete\` 暴露相同值。
   - \`planningHome\`、\`changeRoot\`、\`artifactPaths\` 和 \`actionContext\`：路径和作用域上下文。请使用这些值而非假设仓库本地路径。

   制品 ID 和路径来自活动 schema — 不要假设它们，且不要基于硬编码的制品名称分支。自定义 schema 必须能不加修改地工作。

   要编辑的文件是 \`artifactPaths.<id>.existingOutputPaths\` — 磁盘上存在的具体文件，已对 glob 制品（例如 \`specs/**/*.md\`）进行 glob 展开。不要写入 \`resolvedOutputPath\`：对于 glob 制品，它仍是 glob 模式，而非真实文件。

3. **理解请求**
   - 若用户请求了特定修订（"design 现在使用 X"），那是起始编辑点。
   - 若他们仅说了 "update" / "make this coherent"，将其视为一致性审查：读取现有制品并相互检查矛盾、缺口和重复。

4. **读取并调和**
   - 读取请求涉及的制品以及变更的其他现有制品。
   - 在对话中起草请求的编辑，而非在文件中。明确它究竟改变了什么；步骤 5 负责所有写入。然后对照起草的编辑检查每个其他现有制品 — 在任何方向上：对后续制品的编辑可能需要修订前面的制品，而不仅仅是反过来。构建顺序是方便的阅读顺序，而非对哪些制品可被修订的约束。
   - 记录所有现在不一致、缺失或矛盾的内容。
   - 对已存在的文件（\`existingOutputPaths\`）提出修订。若制品没有现有输出文件且状态为 \`ready\` 或 \`blocked\`，指出它并${CONTINUE_CREATE_THEM}。保持 \`skipped\` 制品不动；不要把它们当作缺失，也不要把它们推迟到 continue 工作流。
   - glob 制品（例如 \`specs/**/*.md\`）在至少一个文件匹配后即标记为 \`done\`，而 continue 工作流只处理 \`ready\` 制品。当调和发现一个 \`existingOutputPaths\` 非空的 glob 制品缺少文件时：
     1. 运行 \`openspec-cn instructions "<artifact-id>" --change "<name>" --json\` 并使用其 \`instruction\` 和 \`template\`。将 \`context\` 和 \`rules\` 视为约束；不要把它们复制进文件。若 instructions 报告 \`skipped: true\`，不要创建文件。从磁盘读取当前依赖文件；若所需的非 skipped 依赖缺失，停止并请用户先恢复它。
     2. 在 \`changeRoot\` 内选择一个符合 \`artifactPaths.<id>.outputPath\` 且尚不存在的具体路径。解析符号链接的父目录后，验证它仍在 \`changeRoot\` 内。glob 的 \`resolvedOutputPath\` 不是有效目标。
     3. 把新文件纳入步骤 5 提议的修订中，仅在用户确认后创建。
     4. 确认后、创建前，刷新 status 和 instructions。验证该制品仍在范围内、未被跳过且已部分填充；重复上述具体路径检查。
     5. 使用一个在目标已存在时会失败的创建操作。若 \`instruction\` 把创建委托给另一个 skill 或命令，仅当它能遵循确认的路径和这些护栏时才调用；否则停止。若任何检查失败或确认的草稿不再有效，停止并与用户调和，而不是替换现有内容或另选路径。
   - 若变更已一致，说明情况且不提议修订。

5. **确认并应用，一次一个制品**
   - 此步骤执行本工作流中的每一次制品写入；此前的步骤都不编辑制品。
   - 展示每个提议的修订及其原因 — 包括步骤 4 中起草的请求编辑。仅在用户确认后写入。
   - 若用户拒绝修订，不要写入 — 保持该制品不变。
   - 当需要重大重写时，先获取该制品的规则和模板：
     \`\`\`bash
     openspec-cn instructions "<artifact-id>" --change "<name>" --json
     \`\`\`

6. **指出下一步（仅供参考 - 绝不要执行）**
   - \`existingOutputPaths\` 为空且状态为 \`ready\` 或 \`blocked\` 的制品 -> ${CONTINUE_NEXT_STEP}。
   - 变更已实现（任务已勾选 / 已 apply） -> 代码可能不再匹配修订后的计划；${APPLY_DELTA_HANDOFF}。
   - 一切完成且已实现 -> ${ARCHIVE_HANDOFF}。

**输出**

每次调用后，展示：
- 修订了哪些制品（以及哪些提议的修订被拒绝）
- 在已部分填充的 glob 制品下创建的任何文件
- ${CONTINUE_DEFERRED}
- 变更的状态及推荐的下一步命令

**护栏**
- 仅规划制品 — 绝不要编辑实现代码。若修订后的计划暗示代码更改，${APPLY_GUARDRAIL}。
- 使用 \`openspec-cn status\` 报告的制品 ID 和路径；绝不要基于硬编码的制品名称分支。
- 仅编辑 \`existingOutputPaths\` 中的具体文件；绝不要写入 glob \`resolvedOutputPath\`。
- 不要推进构建边界：若制品的 \`existingOutputPaths\` 为空且状态为 \`ready\` 或 \`blocked\`，${CONTINUE_FRONTIER}。保持 \`skipped\` 制品不动。新文件的唯一允许范围是 \`existingOutputPaths\` 非空的 glob 制品下一个已确认的具体路径。
- 在写入前与用户确认每个编辑。
- 若请求更改的是变更的*意图*而非细化，${INTENT_CHANGE_GUARDRAIL}。`,
    license: 'MIT',
    compatibility: '需要 openspec-cn CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxUpdateCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Update',
    description: "更新变更 - 修订现有规划制品并保持它们一致（实验性）",
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `修订变更的现有规划制品并保持它们之间一致。绝不要编辑代码。

${STORE_SELECTION_GUIDANCE}

${PROJECT_ROOT_GUARD}

**Input**: 可选地在 \`/opsx:update\` 后指定变更名称（例如 \`/opsx:update add-auth\`）。若省略，检查能否从对话上下文推断。若模糊或歧义，你必须提示用户从可用变更中选择。

${CONTINUE_SCOPE_NOTE}

**步骤**

1. **选择变更**

   若提供了名称，使用它。否则：
   - 从对话上下文推断（若用户提到了某个变更）
   - 若仅有一个活跃变更则自动选择
   - 若存在歧义，运行 \`openspec-cn list --json\` 获取按最近修改排序的可用变更，并让用户选择

   提示时，展示最近修改的前 3-4 个变更作为选项，显示：
   - 变更名称
   - 状态（例如 "0/5 tasks"、"complete"、"no tasks"）
   - 最近修改时间（来自 \`lastModified\` 字段）

   将最近修改的变更标记为 "(推荐)"，因为这很可能是用户想更新的。

   始终宣告："使用变更：<name>"，以及如何覆盖（例如 \`/opsx:update <other>\`）。

2. **获取变更的制品**
   \`\`\`bash
   openspec-cn status --change "<name>" --json
   \`\`\`
   解析 JSON 以理解当前状态。响应包括：
   - \`schemaName\`：使用的工作流 schema（例如 "spec-driven"）
   - \`artifacts\`：制品数组及其状态（"done"、"skipped"、"ready"、"blocked"）
   - \`isPlanningComplete\`：布尔值，表示所有规划制品是否已完成。较旧 CLI 版本以 \`isComplete\` 暴露相同值。
   - \`planningHome\`、\`changeRoot\`、\`artifactPaths\` 和 \`actionContext\`：路径和作用域上下文。请使用这些值而非假设仓库本地路径。

   制品 ID 和路径来自活动 schema — 不要假设它们，且不要基于硬编码的制品名称分支。自定义 schema 必须能不加修改地工作。

   要编辑的文件是 \`artifactPaths.<id>.existingOutputPaths\` — 磁盘上存在的具体文件，已对 glob 制品（例如 \`specs/**/*.md\`）进行 glob 展开。不要写入 \`resolvedOutputPath\`：对于 glob 制品，它仍是 glob 模式，而非真实文件。

3. **理解请求**
   - 若用户请求了特定修订（"design 现在使用 X"），那是起始编辑点。
   - 若他们仅说了 "update" / "make this coherent"，将其视为一致性审查：读取现有制品并相互检查矛盾、缺口和重复。

4. **读取并调和**
   - 读取请求涉及的制品以及变更的其他现有制品。
   - 在对话中起草请求的编辑，而非在文件中。明确它究竟改变了什么；步骤 5 负责所有写入。然后对照起草的编辑检查每个其他现有制品 — 在任何方向上：对后续制品的编辑可能需要修订前面的制品，而不仅仅是反过来。构建顺序是方便的阅读顺序，而非对哪些制品可被修订的约束。
   - 记录所有现在不一致、缺失或矛盾的内容。
   - 对已存在的文件（\`existingOutputPaths\`）提出修订。若制品没有现有输出文件且状态为 \`ready\` 或 \`blocked\`，指出它并${CONTINUE_CREATE_THEM}。保持 \`skipped\` 制品不动；不要把它们当作缺失，也不要把它们推迟到 continue 工作流。
   - glob 制品（例如 \`specs/**/*.md\`）在至少一个文件匹配后即标记为 \`done\`，而 continue 工作流只处理 \`ready\` 制品。当调和发现一个 \`existingOutputPaths\` 非空的 glob 制品缺少文件时：
     1. 运行 \`openspec-cn instructions "<artifact-id>" --change "<name>" --json\` 并使用其 \`instruction\` 和 \`template\`。将 \`context\` 和 \`rules\` 视为约束；不要把它们复制进文件。若 instructions 报告 \`skipped: true\`，不要创建文件。从磁盘读取当前依赖文件；若所需的非 skipped 依赖缺失，停止并请用户先恢复它。
     2. 在 \`changeRoot\` 内选择一个符合 \`artifactPaths.<id>.outputPath\` 且尚不存在的具体路径。解析符号链接的父目录后，验证它仍在 \`changeRoot\` 内。glob 的 \`resolvedOutputPath\` 不是有效目标。
     3. 把新文件纳入步骤 5 提议的修订中，仅在用户确认后创建。
     4. 确认后、创建前，刷新 status 和 instructions。验证该制品仍在范围内、未被跳过且已部分填充；重复上述具体路径检查。
     5. 使用一个在目标已存在时会失败的创建操作。若 \`instruction\` 把创建委托给另一个 skill 或命令，仅当它能遵循确认的路径和这些护栏时才调用；否则停止。若任何检查失败或确认的草稿不再有效，停止并与用户调和，而不是替换现有内容或另选路径。
   - 若变更已一致，说明情况且不提议修订。

5. **确认并应用，一次一个制品**
   - 此步骤执行本工作流中的每一次制品写入；此前的步骤都不编辑制品。
   - 展示每个提议的修订及其原因 — 包括步骤 4 中起草的请求编辑。仅在用户确认后写入。
   - 若用户拒绝修订，不要写入 — 保持该制品不变。
   - 当需要重大重写时，先获取该制品的规则和模板：
     \`\`\`bash
     openspec-cn instructions "<artifact-id>" --change "<name>" --json
     \`\`\`

6. **指出下一步（仅供参考 - 绝不要执行）**
   - \`existingOutputPaths\` 为空且状态为 \`ready\` 或 \`blocked\` 的制品 -> ${CONTINUE_NEXT_STEP}。
   - 变更已实现（任务已勾选 / 已 apply） -> 代码可能不再匹配修订后的计划；${APPLY_DELTA_HANDOFF}。
   - 一切完成且已实现 -> ${ARCHIVE_HANDOFF}。

**输出**

每次调用后，展示：
- 修订了哪些制品（以及哪些提议的修订被拒绝）
- 在已部分填充的 glob 制品下创建的任何文件
- ${CONTINUE_DEFERRED}
- 变更的状态及推荐的下一步命令

**护栏**
- 仅规划制品 — 绝不要编辑实现代码。若修订后的计划暗示代码更改，${APPLY_GUARDRAIL}。
- 使用 \`openspec-cn status\` 报告的制品 ID 和路径；绝不要基于硬编码的制品名称分支。
- 仅编辑 \`existingOutputPaths\` 中的具体文件；绝不要写入 glob \`resolvedOutputPath\`。
- 不要推进构建边界：若制品的 \`existingOutputPaths\` 为空且状态为 \`ready\` 或 \`blocked\`，${CONTINUE_FRONTIER}。保持 \`skipped\` 制品不动。新文件的唯一允许范围是 \`existingOutputPaths\` 非空的 glob 制品下一个已确认的具体路径。
- 在写入前与用户确认每个编辑。
- 若请求更改的是变更的*意图*而非细化，${INTENT_CHANGE_GUARDRAIL}。`
  };
}
