/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getVerifyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-verify-change',
    description: '验证实现是否与变更产出物匹配。当用户想要在归档前验证实现是否完整、正确且一致时使用。',
    instructions: `验证实现是否与变更产出物（规范、任务、设计）匹配。

**输入**：可选指定变更名称。如果省略，检查是否可以从对话上下文中推断。如果模糊或不明确，你**必须**提示获取可用变更。

**步骤**

1. **如果没有提供变更名称，提示选择**

   运行 \`openspec-cn list --json\` 获取可用变更。使用 **AskUserQuestion tool** 让用户选择。

   显示具有实现任务的变更（存在任务产出物）。
   如果可用，包括每个变更使用的 Schema。
   将任务未完成的变更标记为 "(进行中)"。

   **重要提示**：不要猜测或自动选择变更。始终让用户选择。

2. **检查状态以了解 Schema**
   \`\`\`bash
   openspec-cn status --change "<name>" --json
   \`\`\`
   解析 JSON 以了解：
   - \`schemaName\`：正在使用的工作流 Schema（例如："spec-driven"）
   - 此变更存在哪些产出物

3. **获取变更目录并加载产出物**

   \`\`\`bash
   openspec-cn instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and \`contextFiles\` (artifact ID -> array of concrete file paths). Read all available artifacts from \`contextFiles\`.

4. **初始化验证报告结构**

   创建具有三个维度的报告结构：
   - **完整性**：跟踪任务和规范覆盖率
   - **正确性**：跟踪需求实现和场景覆盖率
   - **一致性**：跟踪设计遵循情况和模式一致性

   每个维度可以有 CRITICAL、WARNING 或 SUGGESTION 问题。

5. **验证完整性**

   **Task Completion**:
   - If \`contextFiles.tasks\` exists, read every file path in it
   - Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
   - Count complete vs total tasks
   - If incomplete tasks exist:
     - Add CRITICAL issue for each incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **规范覆盖率**：
   - 如果 \`openspec/changes/<name>/specs/\` 中存在增量规范：
     - 提取所有需求（标记为 "### 需求:"）
     - 对于每个需求：
       - 在代码库中搜索与需求相关的关键词
       - 评估实现是否可能存在
     - 如果需求看起来未实现：
       - 添加 CRITICAL 问题："未找到需求：<需求名称>"
       - 建议："实现需求 X：<描述>"

6. **验证正确性**

   **需求实现映射**：
   - 对于增量规范中的每个需求：
     - 在代码库中搜索实现证据
     - 如果找到，记录文件路径和行范围
     - 评估实现是否符合需求意图
     - 如果检测到偏差：
       - 添加 WARNING："实现可能偏离规范：<详情>"
       - 建议："根据需求 X 审查 <文件>:<行>"

   **场景覆盖率**：
   - 对于增量规范中的每个场景（标记为 "#### 场景:"）：
     - 检查代码中是否处理了条件
     - 检查是否存在覆盖该场景的测试
     - 如果场景看起来未覆盖：
       - 添加 WARNING："场景未覆盖：<场景名称>"
       - 建议："为场景添加测试或实现：<描述>"

7. **验证一致性**

   **Design Adherence**:
   - If \`contextFiles.design\` exists:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no design.md: Skip design adherence check, note "No design.md to verify against"

   **代码模式一致性**：
   - 审查新代码与项目模式的一致性
   - 检查文件命名、目录结构、编码风格
   - 如果发现重大偏差：
     - 添加 SUGGESTION："代码模式偏差：<详情>"
     - 建议："考虑遵循项目模式：<示例>"

8. **生成验证报告**

   **摘要记分卡**：
   \`\`\`
   ## 验证报告：<change-name>

   ### 摘要
   | 维度     | 状态             |
   |----------|------------------|
   | 完整性   | X/Y 任务，N 需求 |
   | 正确性   | M/N 需求已覆盖   |
   | 一致性   | 已遵循/存在问题  |
   \`\`\`

   **按优先级分类的问题**：

   1. **CRITICAL**（归档前必须修复）：
      - 未完成的任务
      - 缺失的需求实现
      - 每个都有具体的、可操作的建议

   2. **WARNING**（应该修复）：
      - 规范/设计偏差
      - 缺失的场景覆盖
      - 每个都有具体的建议

   3. **SUGGESTION**（最好修复）：
      - 模式不一致
      - 小改进
      - 每个都有具体的建议

   **最终评估**：
   - 如果有 CRITICAL 问题："发现 X 个关键问题。归档前请修复。"
   - 如果只有警告："没有关键问题。有 Y 个警告需要考虑。可以归档（但建议改进）。"
   - 如果全部通过："所有检查通过。可以归档。"

**验证启发式方法**

- **完整性**：关注客观的检查清单项（复选框、需求列表）
- **正确性**：使用关键词搜索、文件路径分析、合理推断 - 不要求完全确定
- **一致性**：寻找明显的不一致，不要挑剔风格
- **误报**：不确定时，优先使用 SUGGESTION 而非 WARNING，WARNING 而非 CRITICAL
- **可操作性**：每个问题都必须有具体的建议，并在适用时提供文件/行引用

**优雅降级**

- 如果只存在 tasks.md：仅验证任务完成情况，跳过规范/设计检查
- 如果存在任务 + 规范：验证完整性和正确性，跳过设计
- 如果存在完整产出物：验证所有三个维度
- 始终注明跳过了哪些检查以及原因

**输出格式**

使用清晰的 Markdown：
- 摘要记分卡使用表格
- 问题按组列出（CRITICAL/WARNING/SUGGESTION）
- 代码引用格式：\`file.ts:123\`
- 具体的、可操作的建议
- 不要使用模糊的建议，如 "考虑审查"`,
    license: 'MIT',
    compatibility: '需要 openspec-cn CLI。',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxVerifyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Verify',
    description: '在归档前验证实现是否与变更产出物匹配',
    category: 'Workflow',
    tags: ['workflow', 'verify', 'experimental'],
    content: `验证实现是否与变更产出物（规范、任务、设计）匹配。

**输入**：可选择在 \`/opsx:verify\` 后指定变更名称（例如，\`/opsx:verify add-auth\`）。如果省略，检查是否可以从对话上下文中推断出来。如果模糊或不明确，你必须提示可用的变更。

**步骤**

1. **如果没有提供变更名称，提示选择**

   运行 \`openspec-cn list --json\` 获取可用变更。使用 **AskUserQuestion tool** 让用户选择。

   显示具有实现任务的变更（存在任务产出物）。
   如果可用，包括每个变更使用的 Schema。
   将任务未完成的变更标记为 "(进行中)"。

   **重要提示**：不要猜测或自动选择变更。始终让用户选择。

2. **检查状态以了解 Schema**
   \`\`\`bash
   openspec-cn status --change "<name>" --json
   \`\`\`
   解析 JSON 以了解：
   - \`schemaName\`：正在使用的工作流 Schema（例如："spec-driven"）
   - 此变更存在哪些产出物

3. **获取变更目录并加载产出物**

   \`\`\`bash
   openspec-cn instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and \`contextFiles\` (artifact ID -> array of concrete file paths). Read all available artifacts from \`contextFiles\`.

4. **初始化验证报告结构**

   创建具有三个维度的报告结构：
   - **完整性**：跟踪任务和规范覆盖率
   - **正确性**：跟踪需求实现和场景覆盖率
   - **一致性**：跟踪设计遵循情况和模式一致性

   每个维度可以有 CRITICAL、WARNING 或 SUGGESTION 问题。

5. **验证完整性**

   **Task Completion**:
   - If \`contextFiles.tasks\` exists, read every file path in it
   - Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
   - Count complete vs total tasks
   - If incomplete tasks exist:
     - Add CRITICAL issue for each incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **规范覆盖率**：
   - 如果 \`openspec/changes/<name>/specs/\` 中存在增量规范：
     - 提取所有需求（标记为 "### 需求:"）
     - 对于每个需求：
       - 在代码库中搜索与需求相关的关键词
       - 评估实现是否可能存在
     - 如果需求看起来未实现：
       - 添加 CRITICAL 问题："未找到需求：<需求名称>"
       - 建议："实现需求 X：<描述>"

6. **验证正确性**

   **需求实现映射**：
   - 对于增量规范中的每个需求：
     - 在代码库中搜索实现证据
     - 如果找到，记录文件路径和行范围
     - 评估实现是否符合需求意图
     - 如果检测到偏差：
       - 添加 WARNING："实现可能偏离规范：<详情>"
       - 建议："根据需求 X 审查 <文件>:<行>"

   **场景覆盖率**：
   - 对于增量规范中的每个场景（标记为 "#### 场景:"）：
     - 检查代码中是否处理了条件
     - 检查是否存在覆盖该场景的测试
     - 如果场景看起来未覆盖：
       - 添加 WARNING："场景未覆盖：<场景名称>"
       - 建议："为场景添加测试或实现：<描述>"

7. **验证一致性**

   **Design Adherence**:
   - If \`contextFiles.design\` exists:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no design.md: Skip design adherence check, note "No design.md to verify against"

   **代码模式一致性**：
   - 审查新代码与项目模式的一致性
   - 检查文件命名、目录结构、编码风格
   - 如果发现重大偏差：
     - 添加 SUGGESTION："代码模式偏差：<详情>"
     - 建议："考虑遵循项目模式：<示例>"

8. **生成验证报告**

   **摘要记分卡**：
   \`\`\`
   ## 验证报告：<change-name>

   ### 摘要
   | 维度     | 状态             |
   |----------|------------------|
   | 完整性   | X/Y 任务，N 需求 |
   | 正确性   | M/N 需求已覆盖   |
   | 一致性   | 已遵循/存在问题  |
   \`\`\`

   **按优先级分类的问题**：

   1. **CRITICAL**（归档前必须修复）：
      - 未完成的任务
      - 缺失的需求实现
      - 每个都有具体的、可操作的建议

   2. **WARNING**（应该修复）：
      - 规范/设计偏差
      - 缺失的场景覆盖
      - 每个都有具体的建议

   3. **SUGGESTION**（最好修复）：
      - 模式不一致
      - 小改进
      - 每个都有具体的建议

   **最终评估**：
   - 如果有 CRITICAL 问题："发现 X 个关键问题。归档前请修复。"
   - 如果只有警告："没有关键问题。有 Y 个警告需要考虑。可以归档（但建议改进）。"
   - 如果全部通过："所有检查通过。可以归档。"

**验证启发式方法**

- **完整性**：关注客观的检查清单项（复选框、需求列表）
- **正确性**：使用关键词搜索、文件路径分析、合理推断 - 不要求完全确定
- **一致性**：寻找明显的不一致，不要挑剔风格
- **误报**：不确定时，优先使用 SUGGESTION 而非 WARNING，WARNING 而非 CRITICAL
- **可操作性**：每个问题都必须有具体的建议，并在适用时提供文件/行引用

**优雅降级**

- 如果只存在 tasks.md：仅验证任务完成情况，跳过规范/设计检查
- 如果存在任务 + 规范：验证完整性和正确性，跳过设计
- 如果存在完整产出物：验证所有三个维度
- 始终注明跳过了哪些检查以及原因

**输出格式**

使用清晰的 Markdown：
- 摘要记分卡使用表格
- 问题按组列出（CRITICAL/WARNING/SUGGESTION）
- 代码引用格式：\`file.ts:123\`
- 具体的、可操作的建议
- 不要使用模糊的建议，如 "考虑审查"`
  };
}
