import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import os from 'os';
import path from 'path';
import { promises as fs } from 'fs';
import { parse } from 'yaml';
import {
  includesGitHubCopilot,
  generateCopilotSetupSteps,
  generateCopilotAgentFile,
  COPILOT_CLOUD_FILES,
  removeCopilotCloudFiles,
  writeCopilotCloudFiles,
  readCopilotCloudOptIn,
  hasExistingManagedCloudFiles,
  isCopilotCloudEnabled,
  persistCopilotCloudOptIn,
  findUnmanagedCloudFiles,
  listManagedCloudFiles,
} from '../../src/core/github-copilot/cloud-agent.js';

const MANAGED_MARKER = 'Generated by OpenSpec for GitHub Copilot coding agent support.';

// 由当前生成的 agent 文件派生出一个"上一版本"的无标记 legacy 内容，
// 用于验证这类已识别的 legacy 文件会被刷新/删除。源串来自 generateCopilotAgentFile() 的实际中文输出。
function buildLegacyAgentContent(): string {
  const current = generateCopilotAgentFile();
  const body = current.replace(
    /^<!-- Generated by OpenSpec for GitHub Copilot coding agent support\. -->\n\n/,
    ''
  );
  return body
    .replace(
      '你是一个专门管理 OpenSpec 工作流的智能体。在使用 `openspec-cn` CLI 之前，请先运行 `openspec-cn --version`。若不可用，请通过 `npm install -g @studyzy/openspec-cn` 安装。',
      '你是一个专门管理 OpenSpec 工作流的智能体。你可以通过 shell 命令访问 `openspec-cn` CLI，它已由 `copilot-setup-steps.yml` 预装在开发环境中。'
    )
    .replace(
      '| `openspec-cn archive <change> --json [--yes]` | 归档已完成的变更；仅在确认所有任务均已完成后才使用 `--yes` |',
      '| `openspec-cn archive <change>` | 归档已完成的变更 |'
    );
}
const MARKERLESS_LEGACY_COPILOT_AGENT_FILE = buildLegacyAgentContent();


describe('GitHub Copilot Cloud Agent', () => {
  let tempDir: string;

  function removeManagedMarker(content: string): string {
    const withoutMarker = content
      .replace(/^# Generated by OpenSpec for GitHub Copilot coding agent support\.\n\n/, '')
      .replace(/\n<!-- Generated by OpenSpec for GitHub Copilot coding agent support\. -->\n/, '');
    expect(withoutMarker).not.toBe(content);
    expect(withoutMarker).not.toContain(MANAGED_MARKER);
    return withoutMarker;
  }

  function withCrLf(content: string): string {
    return content.replace(/\n/g, '\r\n');
  }

  async function linkDirectoryOutsideProject(outsideDir: string): Promise<void> {
    await fs.symlink(
      outsideDir,
      path.join(tempDir, '.github'),
      process.platform === 'win32' ? 'junction' : 'dir'
    );
  }

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'openspec-copilot-cloud-agent-'));
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  describe('includesGitHubCopilot', () => {
    it('returns true when github-copilot is in the list', () => {
      expect(includesGitHubCopilot(['claude', 'github-copilot', 'cursor'])).toBe(true);
    });

    it('returns false when github-copilot is not in the list', () => {
      expect(includesGitHubCopilot(['claude', 'cursor'])).toBe(false);
    });

    it('returns false for empty list', () => {
      expect(includesGitHubCopilot([])).toBe(false);
    });
  });

  describe('generateCopilotSetupSteps', () => {
    it('generates a structurally valid Copilot setup workflow', () => {
      const content = generateCopilotSetupSteps();
      const workflow = parse(content);

      expect(workflow).toMatchObject({
        name: 'Copilot Setup Steps',
        on: {
          workflow_dispatch: null,
          push: { paths: ['.github/workflows/copilot-setup-steps.yml'] },
          pull_request: { paths: ['.github/workflows/copilot-setup-steps.yml'] },
        },
        jobs: {
          'copilot-setup-steps': {
            'runs-on': 'ubuntu-latest',
            'timeout-minutes': 10,
            permissions: { contents: 'read' },
          },
        },
      });
      expect(Object.keys(workflow.jobs)).toEqual(['copilot-setup-steps']);
      expect(workflow.jobs['copilot-setup-steps'].steps).toEqual(
        expect.arrayContaining([
          expect.objectContaining({ run: 'npm install -g @studyzy/openspec-cn' }),
          expect.objectContaining({ run: 'openspec-cn --version' }),
        ])
      );
    });
  });

  describe('generateCopilotAgentFile', () => {
    it('generates valid agent frontmatter and non-interactive guidance', () => {
      const content = generateCopilotAgentFile();
      const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---\n/);
      expect(frontmatterMatch).not.toBeNull();
      const frontmatter = parse(frontmatterMatch![1]);

      expect(frontmatter).toEqual({
        name: 'OpenSpec',
        description: expect.any(String),
        tools: ['execute', 'read', 'search', 'edit'],
      });
      expect(content).toContain('Generated by OpenSpec for GitHub Copilot coding agent support.');
      expect(content).toContain('# OpenSpec 智能体');
      expect(content).toContain('openspec-cn list');
      expect(content).toContain('openspec-cn new change <name>');
      expect(content).toContain('openspec-cn status --change <name> --json');
      expect(content).toContain('openspec-cn instructions [artifact] --change <name> --json');
      expect(content).toContain('openspec-cn archive <change> --json [--yes]');
      expect(content).toContain('仅在确认所有任务均已完成后才使用 `--yes`');
      expect(content).toContain('运行 `openspec-cn --version`');
      expect(content).not.toContain('pre-installed in the development environment');
      expect(content).not.toContain('Create the change directory under');
      expect(content).toContain('openspec-cn validate');
    });
  });

  describe('COPILOT_CLOUD_FILES', () => {
    it('has correct file paths', () => {
      expect(COPILOT_CLOUD_FILES.setupSteps).toBe(path.join('.github', 'workflows', 'copilot-setup-steps.yml'));
      expect(COPILOT_CLOUD_FILES.agent).toBe(path.join('.github', 'agents', 'openspec.agent.md'));
    });
  });

  describe('writeCopilotCloudFiles', () => {
    it('writes missing cloud files and creates parent directories', async () => {
      const result = await writeCopilotCloudFiles(tempDir);

      expect(result).toEqual({ setupStepsWritten: true, agentWritten: true });
      await expect(fs.stat(path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps))).resolves.toBeTruthy();
      await expect(fs.stat(path.join(tempDir, COPILOT_CLOUD_FILES.agent))).resolves.toBeTruthy();
    });

    it('preserves customized existing files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, 'custom setup');
      await fs.writeFile(agentPath, 'custom agent');

      const result = await writeCopilotCloudFiles(tempDir);

      expect(result).toEqual({ setupStepsWritten: false, agentWritten: false });
      await expect(fs.readFile(setupStepsPath, 'utf8')).resolves.toBe('custom setup');
      await expect(fs.readFile(agentPath, 'utf8')).resolves.toBe('custom agent');
    });

    it('creates robust agent guidance alongside a customized setup workflow', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      const customSetup = 'name: custom setup\n';
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.writeFile(setupStepsPath, customSetup);

      const result = await writeCopilotCloudFiles(tempDir);

      expect(result).toEqual({ setupStepsWritten: false, agentWritten: true });
      await expect(fs.readFile(setupStepsPath, 'utf8')).resolves.toBe(customSetup);
      const agentContent = await fs.readFile(agentPath, 'utf8');
      expect(agentContent).toContain('运行 `openspec-cn --version`');
      expect(agentContent).toContain('请通过 `npm install -g @studyzy/openspec-cn`');
      expect(agentContent).not.toContain('pre-installed in the development environment');
    });

    it('preserves an alternate user-owned agent with the same Copilot identifier', async () => {
      const alternateAgentPath = path.join(tempDir, '.github', 'agents', 'openspec.md');
      const generatedAgentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      const customAgent = 'user-owned OpenSpec agent\n';
      await fs.mkdir(path.dirname(alternateAgentPath), { recursive: true });
      await fs.writeFile(alternateAgentPath, customAgent);

      const result = await writeCopilotCloudFiles(tempDir);

      expect(result).toEqual({ setupStepsWritten: true, agentWritten: false });
      await expect(fs.readFile(alternateAgentPath, 'utf8')).resolves.toBe(customAgent);
      await expect(fs.stat(generatedAgentPath)).rejects.toMatchObject({ code: 'ENOENT' });
    });

    it('removes a managed agent when an alternate user-owned agent is added later', async () => {
      const alternateAgentPath = path.join(tempDir, '.github', 'agents', 'openspec.md');
      const generatedAgentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      const customAgent = 'user-owned OpenSpec agent\n';
      await writeCopilotCloudFiles(tempDir);
      await fs.writeFile(alternateAgentPath, customAgent);

      const result = await writeCopilotCloudFiles(tempDir);

      expect(result).toEqual({ setupStepsWritten: false, agentWritten: false });
      await expect(fs.readFile(alternateAgentPath, 'utf8')).resolves.toBe(customAgent);
      await expect(fs.stat(generatedAgentPath)).rejects.toMatchObject({ code: 'ENOENT' });
    });

    it('reports conflicting user-owned agent profiles without creating setup files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const alternateAgentPath = path.join(tempDir, '.github', 'agents', 'openspec.md');
      const generatedAgentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(alternateAgentPath), { recursive: true });
      await fs.writeFile(alternateAgentPath, 'custom alternate agent\n');
      await fs.writeFile(generatedAgentPath, 'custom generated-path agent\n');

      await expect(writeCopilotCloudFiles(tempDir)).rejects.toThrow(
        'Copilot 代理配置文件冲突：'
      );

      await expect(fs.stat(setupStepsPath)).rejects.toMatchObject({ code: 'ENOENT' });
      await expect(fs.readFile(alternateAgentPath, 'utf8')).resolves.toBe(
        'custom alternate agent\n'
      );
      await expect(fs.readFile(generatedAgentPath, 'utf8')).resolves.toBe(
        'custom generated-path agent\n'
      );
    });

    it('rejects a directory at a managed file path before creating other files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(agentPath, { recursive: true });

      await expect(writeCopilotCloudFiles(tempDir)).rejects.toThrow(
        '受管理的 Copilot 路径不是常规文件：'
      );

      await expect(fs.stat(setupStepsPath)).rejects.toMatchObject({ code: 'ENOENT' });
      expect((await fs.stat(agentPath)).isDirectory()).toBe(true);
    });

    it('refreshes exact legacy generated files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, removeManagedMarker(generateCopilotSetupSteps()));
      await fs.writeFile(agentPath, MARKERLESS_LEGACY_COPILOT_AGENT_FILE);

      const result = await writeCopilotCloudFiles(tempDir);

      expect(result).toEqual({ setupStepsWritten: true, agentWritten: true });
      await expect(fs.readFile(setupStepsPath, 'utf8')).resolves.toBe(
        generateCopilotSetupSteps()
      );
      await expect(fs.readFile(agentPath, 'utf8')).resolves.toBe(generateCopilotAgentFile());
    });

    it('refreshes the previous marker-bearing generated agent', async () => {
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      const previousAgent = generateCopilotAgentFile()
        .replace(
          '你是一个专门管理 OpenSpec 工作流的智能体。在使用 `openspec-cn` CLI 之前，请先运行 `openspec-cn --version`。若不可用，请通过 `npm install -g @studyzy/openspec-cn` 安装。',
          '你是一个专门管理 OpenSpec 工作流的智能体。你可以通过 shell 命令访问 `openspec-cn` CLI，它已由 `copilot-setup-steps.yml` 预装在开发环境中。'
        )
        .replace(
          '| `openspec-cn archive <change> --json [--yes]` | 归档已完成的变更；仅在确认所有任务均已完成后才使用 `--yes` |',
          '| `openspec-cn archive <change>` | 归档已完成的变更 |'
        );
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(agentPath, previousAgent);

      const result = await writeCopilotCloudFiles(tempDir);

      expect(result.agentWritten).toBe(true);
      await expect(fs.readFile(agentPath, 'utf8')).resolves.toBe(generateCopilotAgentFile());
    });

    it('leaves current generated files unchanged, including CRLF content', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      const setupStepsContent = generateCopilotSetupSteps();
      const agentContent = withCrLf(generateCopilotAgentFile());
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, setupStepsContent);
      await fs.writeFile(agentPath, agentContent);

      const result = await writeCopilotCloudFiles(tempDir);

      expect(result).toEqual({ setupStepsWritten: false, agentWritten: false });
      await expect(fs.readFile(setupStepsPath, 'utf8')).resolves.toBe(setupStepsContent);
      await expect(fs.readFile(agentPath, 'utf8')).resolves.toBe(agentContent);
    });

    it('refuses to write cloud files through a linked .github directory', async () => {
      const outsideDir = await fs.mkdtemp(path.join(os.tmpdir(), 'openspec-copilot-outside-'));
      const outsideSetupStepsPath = path.join(
        outsideDir,
        'workflows',
        'copilot-setup-steps.yml'
      );
      const outsideAgentPath = path.join(outsideDir, 'agents', 'openspec.agent.md');

      try {
        await linkDirectoryOutsideProject(outsideDir);

        await expect(writeCopilotCloudFiles(tempDir)).rejects.toThrow(
          '路径位于允许的目录之外'
        );
        await expect(fs.stat(outsideSetupStepsPath)).rejects.toMatchObject({ code: 'ENOENT' });
        await expect(fs.stat(outsideAgentPath)).rejects.toMatchObject({ code: 'ENOENT' });
      } finally {
        await fs.rm(outsideDir, { recursive: true, force: true });
      }
    });
  });

  describe('removeCopilotCloudFiles', () => {
    it('removes only existing cloud files and returns the removal count', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await writeCopilotCloudFiles(tempDir);
      await fs.rm(agentPath, { force: true });

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(1);
      await expect(fs.stat(setupStepsPath)).rejects.toMatchObject({ code: 'ENOENT' });
      await expect(fs.stat(agentPath)).rejects.toMatchObject({ code: 'ENOENT' });
    });

    it('keeps customized cloud files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, 'custom setup');
      await fs.writeFile(agentPath, 'custom agent');

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(0);
      await expect(fs.readFile(setupStepsPath, 'utf8')).resolves.toBe('custom setup');
      await expect(fs.readFile(agentPath, 'utf8')).resolves.toBe('custom agent');
    });

    it('keeps modified marker-bearing cloud files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, `${generateCopilotSetupSteps()}\n# custom change\n`);
      await fs.writeFile(agentPath, `${generateCopilotAgentFile()}\ncustom change\n`);

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(0);
      await expect(fs.readFile(setupStepsPath, 'utf8')).resolves.toContain('custom change');
      await expect(fs.readFile(agentPath, 'utf8')).resolves.toContain('custom change');
    });

    it('removes markerless current generated cloud files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, removeManagedMarker(generateCopilotSetupSteps()));
      await fs.writeFile(agentPath, removeManagedMarker(generateCopilotAgentFile()));

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(2);
      await expect(fs.stat(setupStepsPath)).rejects.toMatchObject({ code: 'ENOENT' });
      await expect(fs.stat(agentPath)).rejects.toMatchObject({ code: 'ENOENT' });
    });

    it('removes markerless legacy generated cloud files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      const currentAgentContent = removeManagedMarker(generateCopilotAgentFile());
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, removeManagedMarker(generateCopilotSetupSteps()));
      await fs.writeFile(agentPath, MARKERLESS_LEGACY_COPILOT_AGENT_FILE);

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(MARKERLESS_LEGACY_COPILOT_AGENT_FILE).not.toBe(currentAgentContent);
      expect(MARKERLESS_LEGACY_COPILOT_AGENT_FILE).toContain('你可以通过 shell 命令访问');
      expect(removed).toBe(2);
      await expect(fs.stat(setupStepsPath)).rejects.toMatchObject({ code: 'ENOENT' });
      await expect(fs.stat(agentPath)).rejects.toMatchObject({ code: 'ENOENT' });
    });

    it('removes current and legacy generated cloud files with CRLF line endings', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, withCrLf(generateCopilotSetupSteps()));
      await fs.writeFile(agentPath, withCrLf(MARKERLESS_LEGACY_COPILOT_AGENT_FILE));

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(2);
      await expect(fs.stat(setupStepsPath)).rejects.toMatchObject({ code: 'ENOENT' });
      await expect(fs.stat(agentPath)).rejects.toMatchObject({ code: 'ENOENT' });
    });

    it('keeps customized cloud files with CRLF line endings', async () => {
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      const customizedContent = withCrLf(`${generateCopilotAgentFile()}\ncustom change\n`);
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(agentPath, customizedContent);

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(0);
      await expect(fs.readFile(agentPath, 'utf8')).resolves.toBe(customizedContent);
    });

    it('preserves the alternate user-owned agent during cleanup', async () => {
      const alternateAgentPath = path.join(tempDir, '.github', 'agents', 'openspec.md');
      const customAgent = 'user-owned OpenSpec agent\n';
      await fs.mkdir(path.dirname(alternateAgentPath), { recursive: true });
      await fs.writeFile(alternateAgentPath, customAgent);

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(0);
      await expect(fs.readFile(alternateAgentPath, 'utf8')).resolves.toBe(customAgent);
    });

    it('preflights nested linked paths before removing any managed file', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentsDir = path.join(tempDir, '.github', 'agents');
      const outsideDir = await fs.mkdtemp(path.join(os.tmpdir(), 'openspec-copilot-outside-'));
      const outsideAgentPath = path.join(outsideDir, 'openspec.agent.md');
      const setupStepsContent = generateCopilotSetupSteps();
      const agentContent = generateCopilotAgentFile();

      try {
        await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
        await fs.writeFile(setupStepsPath, setupStepsContent);
        await fs.writeFile(outsideAgentPath, agentContent);
        await fs.symlink(
          outsideDir,
          agentsDir,
          process.platform === 'win32' ? 'junction' : 'dir'
        );

        await expect(removeCopilotCloudFiles(tempDir)).rejects.toThrow(
          '路径位于允许的目录之外'
        );
        await expect(fs.readFile(setupStepsPath, 'utf8')).resolves.toBe(setupStepsContent);
        await expect(fs.readFile(outsideAgentPath, 'utf8')).resolves.toBe(agentContent);
      } finally {
        await fs.rm(outsideDir, { recursive: true, force: true });
      }
    });

    it('refuses to remove managed cloud files through a linked .github directory', async () => {
      const outsideDir = await fs.mkdtemp(path.join(os.tmpdir(), 'openspec-copilot-outside-'));
      const outsideSetupStepsPath = path.join(
        outsideDir,
        'workflows',
        'copilot-setup-steps.yml'
      );
      const outsideAgentPath = path.join(outsideDir, 'agents', 'openspec.agent.md');
      const setupStepsContent = generateCopilotSetupSteps();
      const agentContent = generateCopilotAgentFile();

      try {
        await fs.mkdir(path.dirname(outsideSetupStepsPath), { recursive: true });
        await fs.mkdir(path.dirname(outsideAgentPath), { recursive: true });
        await fs.writeFile(outsideSetupStepsPath, setupStepsContent);
        await fs.writeFile(outsideAgentPath, agentContent);
        await linkDirectoryOutsideProject(outsideDir);

        await expect(removeCopilotCloudFiles(tempDir)).rejects.toThrow(
          '路径位于允许的目录之外'
        );
        await expect(fs.readFile(outsideSetupStepsPath, 'utf8')).resolves.toBe(
          setupStepsContent
        );
        await expect(fs.readFile(outsideAgentPath, 'utf8')).resolves.toBe(agentContent);
      } finally {
        await fs.rm(outsideDir, { recursive: true, force: true });
      }
    });
  });

  describe('cloud opt-in', () => {
    const CONFIG_WITH_COMMENTS = `schema: spec-driven

# Project context (optional)
context: |
  Tech stack: TypeScript
`;

    async function writeConfig(content: string): Promise<string> {
      const configPath = path.join(tempDir, 'openspec', 'config.yaml');
      await fs.mkdir(path.dirname(configPath), { recursive: true });
      await fs.writeFile(configPath, content);
      return configPath;
    }

    describe('readCopilotCloudOptIn', () => {
      it('returns undefined when there is no config', () => {
        expect(readCopilotCloudOptIn(tempDir)).toBeUndefined();
      });

      it('reads an explicit opt-in and opt-out', async () => {
        await writeConfig(`${CONFIG_WITH_COMMENTS}githubCopilot:\n  cloudAgent: true\n`);
        expect(readCopilotCloudOptIn(tempDir)).toBe(true);

        await writeConfig(`${CONFIG_WITH_COMMENTS}githubCopilot:\n  cloudAgent: false\n`);
        expect(readCopilotCloudOptIn(tempDir)).toBe(false);
      });

      it('treats a non-boolean value as undecided', async () => {
        await writeConfig(`${CONFIG_WITH_COMMENTS}githubCopilot:\n  cloudAgent: "yes"\n`);
        expect(readCopilotCloudOptIn(tempDir)).toBeUndefined();
      });
    });

    describe('persistCopilotCloudOptIn', () => {
      it('writes the nested key while preserving existing comments and content', async () => {
        const configPath = await writeConfig(CONFIG_WITH_COMMENTS);

        await persistCopilotCloudOptIn(tempDir, true);

        const written = await fs.readFile(configPath, 'utf8');
        expect(written).toContain('# Project context (optional)');
        expect(written).toContain('Tech stack: TypeScript');
        expect(parse(written)).toMatchObject({
          schema: 'spec-driven',
          githubCopilot: { cloudAgent: true },
        });
        // Round-trips through the reader.
        expect(readCopilotCloudOptIn(tempDir)).toBe(true);
      });

      it('flips an existing decision in place', async () => {
        await writeConfig(`${CONFIG_WITH_COMMENTS}githubCopilot:\n  cloudAgent: true\n`);
        await persistCopilotCloudOptIn(tempDir, false);
        expect(readCopilotCloudOptIn(tempDir)).toBe(false);
      });

      it('is a no-op when no config file exists', async () => {
        await persistCopilotCloudOptIn(tempDir, true);
        await expect(
          fs.stat(path.join(tempDir, 'openspec', 'config.yaml'))
        ).rejects.toMatchObject({ code: 'ENOENT' });
      });

      it('persists into and reads from config.yml when only .yml exists', async () => {
        const ymlPath = path.join(tempDir, 'openspec', 'config.yml');
        await fs.mkdir(path.dirname(ymlPath), { recursive: true });
        await fs.writeFile(ymlPath, `${CONFIG_WITH_COMMENTS}`);

        await persistCopilotCloudOptIn(tempDir, true);

        // No sibling .yaml was created; the .yml file was edited in place.
        await expect(
          fs.stat(path.join(tempDir, 'openspec', 'config.yaml'))
        ).rejects.toMatchObject({ code: 'ENOENT' });
        const written = await fs.readFile(ymlPath, 'utf8');
        expect(written).toContain('# Project context (optional)');
        expect(written).toContain('cloudAgent: true');
        expect(readCopilotCloudOptIn(tempDir)).toBe(true);
      });

      it('does not throw on a scalar-content config and writes a valid map', async () => {
        // A degenerate config whose top-level node is a bare scalar used to
        // throw "Expected a YAML collection as document contents".
        await writeConfig('null\n');
        await expect(persistCopilotCloudOptIn(tempDir, false)).resolves.toBeUndefined();
        expect(readCopilotCloudOptIn(tempDir)).toBe(false);
      });

      it('does not throw on a sequence-root config and writes a valid map', async () => {
        // A YAML list at the root is also not a map: setIn would throw, so it
        // must be replaced with a fresh document rather than crash.
        await writeConfig('- a\n- b\n');
        await expect(persistCopilotCloudOptIn(tempDir, true)).resolves.toBeUndefined();
        expect(readCopilotCloudOptIn(tempDir)).toBe(true);
      });

      it('leaves an unparseable config untouched instead of throwing', async () => {
        // A multi-document stream can't be edited without corrupting it; persist
        // must skip it (no throw, no clobber) rather than crash.
        const malformed = '---\na: 1\n---\nb: 2\n';
        const configPath = await writeConfig(malformed);

        await expect(persistCopilotCloudOptIn(tempDir, true)).resolves.toBeUndefined();

        expect(await fs.readFile(configPath, 'utf8')).toBe(malformed);
      });

      it('does not throw when the githubCopilot node itself is not a map', async () => {
        // Root is a valid map, but `githubCopilot` holds a scalar/null/sequence:
        // descending into it with setIn used to throw. Each must be replaced
        // with a map, keeping the rest of the config (and its comments) intact.
        for (const bad of [
          'githubCopilot: false',
          'githubCopilot: null',
          'githubCopilot:\n  - a\n  - b',
        ]) {
          await writeConfig(`schema: spec-driven\n# keep me\n${bad}\n`);
          await expect(persistCopilotCloudOptIn(tempDir, true)).resolves.toBeUndefined();
          expect(readCopilotCloudOptIn(tempDir)).toBe(true);
          const written = await fs.readFile(
            path.join(tempDir, 'openspec', 'config.yaml'),
            'utf8'
          );
          expect(written).toContain('# keep me');
          expect(written).toContain('schema: spec-driven');
        }
      });
    });

    describe('listManagedCloudFiles', () => {
      it('is empty on a clean project and lists managed files after a write', async () => {
        await expect(listManagedCloudFiles(tempDir)).resolves.toEqual([]);
        await writeCopilotCloudFiles(tempDir);
        await expect(listManagedCloudFiles(tempDir)).resolves.toEqual([
          COPILOT_CLOUD_FILES.setupSteps,
          COPILOT_CLOUD_FILES.agent,
        ]);
      });

      it('excludes a user-owned (non-managed) file', async () => {
        await writeCopilotCloudFiles(tempDir);
        await fs.writeFile(
          path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps),
          'name: my own build workflow\n'
        );
        await expect(listManagedCloudFiles(tempDir)).resolves.toEqual([COPILOT_CLOUD_FILES.agent]);
      });
    });

    describe('findUnmanagedCloudFiles', () => {
      it('is empty on a clean project and after a managed write', async () => {
        await expect(findUnmanagedCloudFiles(tempDir)).resolves.toEqual([]);
        await writeCopilotCloudFiles(tempDir);
        await expect(findUnmanagedCloudFiles(tempDir)).resolves.toEqual([]);
      });

      it('reports a user-owned (non-managed) file that would be left untouched', async () => {
        const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
        await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
        await fs.writeFile(setupStepsPath, 'name: my own build workflow\n');

        await expect(findUnmanagedCloudFiles(tempDir)).resolves.toEqual([
          COPILOT_CLOUD_FILES.setupSteps,
        ]);
      });
    });

    describe('hasExistingManagedCloudFiles', () => {
      it('is false on a clean project', async () => {
        await expect(hasExistingManagedCloudFiles(tempDir)).resolves.toBe(false);
      });

      it('is true when a managed file exists, false for a purely customized one', async () => {
        await writeCopilotCloudFiles(tempDir);
        await expect(hasExistingManagedCloudFiles(tempDir)).resolves.toBe(true);

        // Replace both managed files with customized content: no longer "managed".
        await fs.writeFile(
          path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps),
          'name: my own workflow\n'
        );
        await fs.writeFile(
          path.join(tempDir, COPILOT_CLOUD_FILES.agent),
          'my own agent instructions\n'
        );
        await expect(hasExistingManagedCloudFiles(tempDir)).resolves.toBe(false);
      });
    });

    describe('isCopilotCloudEnabled', () => {
      it('honors an explicit opt-out even when managed files exist', async () => {
        await writeCopilotCloudFiles(tempDir);
        await writeConfig(`${CONFIG_WITH_COMMENTS}githubCopilot:\n  cloudAgent: false\n`);
        await expect(isCopilotCloudEnabled(tempDir)).resolves.toBe(false);
      });

      it('honors an explicit opt-in with no files yet', async () => {
        await writeConfig(`${CONFIG_WITH_COMMENTS}githubCopilot:\n  cloudAgent: true\n`);
        await expect(isCopilotCloudEnabled(tempDir)).resolves.toBe(true);
      });

      it('falls back to existing managed files when undecided (migration)', async () => {
        await writeCopilotCloudFiles(tempDir);
        await expect(isCopilotCloudEnabled(tempDir)).resolves.toBe(true);
      });

      it('is false when undecided and no managed files exist', async () => {
        await expect(isCopilotCloudEnabled(tempDir)).resolves.toBe(false);
      });
    });
  });
});
