/**
 * GitHub Copilot Cloud Agent Support
 *
 * Generates copilot-setup-steps.yml and .github/agents/openspec.agent.md
 * when the github-copilot tool is selected during init/update.
 * These files enable the GitHub Copilot coding agent (cloud) to use the
 * OpenSpec CLI in its ephemeral dev environment.
 */

import path from 'path';
import { promises as fs } from 'fs';
import { Document, YAMLMap, parseDocument, isMap } from 'yaml';
import { FileSystemUtils } from '../../utils/file-system.js';
import { readProjectConfig, resolveConfigFilePath } from '../project-config.js';

const COPILOT_TOOL_ID = 'github-copilot';
const OPENSPEC_MANAGED_MARKER = 'Generated by OpenSpec for GitHub Copilot coding agent support.';

/**
 * Check if a tool list includes github-copilot.
 */
export function includesGitHubCopilot(toolIds: string[]): boolean {
  return toolIds.includes(COPILOT_TOOL_ID);
}

/**
 * Generate the copilot-setup-steps.yml workflow file content.
 * This workflow pre-installs the OpenSpec CLI in the Copilot coding agent's
 * ephemeral GitHub Actions environment.
 */
export function generateCopilotSetupSteps(): string {
  return `# ${OPENSPEC_MANAGED_MARKER}

${generateCopilotSetupStepsBody()}`;
}

function generateCopilotSetupStepsBody(): string {
  return `name: "Copilot Setup Steps"

# Runs automatically when changed (for validation) and can be triggered manually.
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called \`copilot-setup-steps\` for Copilot coding agent to pick it up.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenSpec CLI
        run: npm install -g @studyzy/openspec-cn

      - name: Verify OpenSpec CLI
        run: openspec-cn --version
`;
}

/**
 * Generate the .github/agents/openspec.agent.md custom agent file content.
 * This tells the GitHub Copilot coding agent how to use the OpenSpec CLI.
 */
export function generateCopilotAgentFile(): string {
  return generateCopilotAgentFileBody(true);
}

function generateCopilotAgentFileBody(includeManagedMarker = false): string {
  const managedMarker = includeManagedMarker
    ? `<!-- ${OPENSPEC_MANAGED_MARKER} -->\n\n`
    : '';

  return `---
name: OpenSpec
description: "使用 OpenSpec CLI 管理 OpenSpec 的变更、spec 和工作流。可用此智能体提议变更、探索想法、校验制品、检查状态以及归档已完成的工作。"
tools:
  - "execute"
  - "read"
  - "search"
  - "edit"
---

${managedMarker}# OpenSpec 智能体

你是一个专门管理 OpenSpec 工作流的智能体。在使用 \`openspec-cn\` CLI 之前，请先运行 \`openspec-cn --version\`。若不可用，请通过 \`npm install -g @studyzy/openspec-cn\` 安装。

## 什么是 OpenSpec？

OpenSpec 是面向代码库的结构化变更管理系统。它将工作组织为**变更**，并配有指导实现的规划制品（提案、spec、设计、任务）。

## 可用命令

### 适合智能体的 CLI 命令（建议使用 \`--json\` 获取结构化输出）

| 命令 | 用途 |
|---------|---------|
| \`openspec-cn list [--json]\` | 列出所有变更和 spec |
| \`openspec-cn show <item> [--json]\` | 查看特定的变更或 spec |
| \`openspec-cn validate [--all] [--json]\` | 校验变更和 spec 是否存在问题 |
| \`openspec-cn status [--change <name>] [--json]\` | 显示某个变更的制品进度 |
| \`openspec-cn instructions [artifact] [--change <name>] [--json]\` | 获取某个变更的下一步指令 |
| \`openspec-cn templates [--json]\` | 列出可用模板 |
| \`openspec-cn schemas [--json]\` | 列出可用的工作流 schema |
| \`openspec-cn archive <change> --json [--yes]\` | 归档已完成的变更；仅在确认所有任务均已完成后才使用 \`--yes\` |

### 交互式 CLI 命令（在用户要求时使用）

| 命令 | 用途 |
|---------|---------|
| \`openspec-cn init\` | 在项目中初始化 OpenSpec |
| \`openspec-cn update\` | 更新 OpenSpec 配置与制品 |
| \`openspec-cn view\` | 交互式仪表盘 |
| \`openspec-cn config\` | 查看或修改设置 |

## 工作流

当被要求使用 OpenSpec 工作时，请遵循以下模式：

1. **找到变更**：运行 \`openspec-cn list --json\` 查看活跃的变更。
2. **检查进度**：对选定的变更运行 \`openspec-cn status --change <name> --json\`。
3. **遵循指令**：运行 \`openspec-cn instructions [artifact] --change <name> --json\` 获取下一个制品的指令。
4. **完成前校验**：运行 \`openspec-cn validate <name> --json\`。

## 创建新变更

当用户想要提议一个新变更时：

1. 运行 \`openspec-cn new change <name>\`。
2. 运行 \`openspec-cn status --change <name> --json\` 查看制品顺序。
3. 在创建每个制品之前，使用 \`openspec-cn instructions [artifact] --change <name> --json\`。
4. 制品完成后运行 \`openspec-cn validate <name> --json\`。

## 关键目录

- \`openspec/\` — OpenSpec 根目录
- \`openspec/changes/\` — 活跃变更及其制品
- \`openspec/config.yaml\` — 项目配置

## 最佳实践

- 当需要以程序方式解析输出时，始终使用 \`--json\` 标志
- 创建或修改制品后运行 \`openspec-cn validate\`
- 开始工作前先检查 \`openspec-cn status\` 以了解当前状态
- 归档时，请先确保所有任务均已完成并通过校验
`;
}

function generatePreviousCopilotAgentFileBody(includeManagedMarker = false): string {
  let content = generateCopilotAgentFileBody();
  content = replaceRequired(
    content,
    '你是一个专门管理 OpenSpec 工作流的智能体。在使用 `openspec-cn` CLI 之前，请先运行 `openspec-cn --version`。若不可用，请通过 `npm install -g @studyzy/openspec-cn` 安装。',
    '你是一个专门管理 OpenSpec 工作流的智能体。你可以通过 shell 命令访问 `openspec-cn` CLI，它已由 `copilot-setup-steps.yml` 预装在开发环境中。',
    'previous CLI access sentence'
  );
  content = replaceRequired(
    content,
    '| `openspec-cn archive <change> --json [--yes]` | 归档已完成的变更；仅在确认所有任务均已完成后才使用 `--yes` |',
    '| `openspec-cn archive <change>` | 归档已完成的变更 |',
    'previous archive command row'
  );

  if (!includeManagedMarker) {
    return content;
  }

  return replaceRequired(
    content,
    '\n# OpenSpec 智能体',
    `\n<!-- ${OPENSPEC_MANAGED_MARKER} -->\n\n# OpenSpec 智能体`,
    'previous agent heading'
  );
}

function generateLegacyCopilotAgentFileBody(): string {
  let content = generatePreviousCopilotAgentFileBody();
  content = replaceRequired(
    content,
    `## 工作流

当被要求使用 OpenSpec 工作时，请遵循以下模式：

1. **找到变更**：运行 \`openspec-cn list --json\` 查看活跃的变更。
2. **检查进度**：对选定的变更运行 \`openspec-cn status --change <name> --json\`。
3. **遵循指令**：运行 \`openspec-cn instructions [artifact] --change <name> --json\` 获取下一个制品的指令。
4. **完成前校验**：运行 \`openspec-cn validate <name> --json\`。

## 创建新变更

当用户想要提议一个新变更时：

1. 运行 \`openspec-cn new change <name>\`。
2. 运行 \`openspec-cn status --change <name> --json\` 查看制品顺序。
3. 在创建每个制品之前，使用 \`openspec-cn instructions [artifact] --change <name> --json\`。
4. 制品完成后运行 \`openspec-cn validate <name> --json\`。`,
    `## 工作流

当被要求使用 OpenSpec 工作时，请遵循以下模式：

1. **检查当前状态**：运行 \`openspec-cn status --json\` 了解存在哪些变更及其进度。
2. **遵循指令**：运行 \`openspec-cn instructions --json\` 获取结合上下文的下一步操作。
3. **完成前校验**：运行 \`openspec-cn validate --all --json\` 确保制品正确。

## 创建新变更

当用户想要提议一个新变更时：

1. 在 \`openspec/changes/<change-name>/\` 下创建变更目录
2. 根据项目配置的工作流 schema 生成所需的规划制品
3. 运行 \`openspec-cn validate --json\` 验证制品格式是否正确`,
    'legacy workflow guidance'
  );
  content = replaceRequired(
    content,
    `tools:
  - "execute"
  - "read"
  - "search"
  - "edit"`,
    `tools:
  - "terminal"`,
    'legacy tool alias'
  );
  content = replaceRequired(
    content,
    '你是一个专门管理 OpenSpec 工作流的智能体。你可以通过 shell 命令访问 `openspec-cn` CLI，它已由 `copilot-setup-steps.yml` 预装在开发环境中。',
    '你是一个专门管理 OpenSpec 工作流的智能体。你可以访问 `openspec-cn` CLI，它已由 `copilot-setup-steps.yml` 预装在开发环境中。',
    'legacy CLI access sentence'
  );
  content = replaceRequired(
    content,
    '| `openspec-cn status [--change <name>] [--json]` | 显示某个变更的制品进度 |',
    '| `openspec-cn status [--json]` | 显示活跃变更的制品进度 |',
    'legacy status command row'
  );
  content = replaceRequired(
    content,
    '| `openspec-cn instructions [artifact] [--change <name>] [--json]` | 获取某个变更的下一步指令 |',
    '| `openspec-cn instructions [--json]` | 获取某个变更的下一步指令 |',
    'legacy instructions command row'
  );
  return replaceRequired(
    content,
    '- `openspec/config.yaml` — 项目配置',
    `- \`openspec/config.yaml\` — 项目配置
- \`openspec/explorations/\` — 探索文档`,
    'legacy exploration directory'
  );
}

function replaceRequired(
  content: string,
  searchValue: string,
  replaceValue: string,
  label: string
): string {
  if (!content.includes(searchValue)) {
    throw new Error(`无法构建 Copilot 云文件内容：缺少 ${label}`);
  }
  return content.replace(searchValue, replaceValue);
}

/**
 * File paths (relative to project root) for the generated files.
 */
export const COPILOT_CLOUD_FILES = {
  setupSteps: path.join('.github', 'workflows', 'copilot-setup-steps.yml'),
  agent: path.join('.github', 'agents', 'openspec.agent.md'),
} as const;

const COPILOT_AGENT_ALTERNATE_FILE = path.join('.github', 'agents', 'openspec.md');

type CopilotCloudFile = (typeof COPILOT_CLOUD_FILES)[keyof typeof COPILOT_CLOUD_FILES];

const COPILOT_CLOUD_FILE_CONTENTS: Record<CopilotCloudFile, string> = {
  [COPILOT_CLOUD_FILES.setupSteps]: generateCopilotSetupSteps(),
  [COPILOT_CLOUD_FILES.agent]: generateCopilotAgentFile(),
};

function getLegacyCopilotCloudFileContents(relPath: CopilotCloudFile): string[] {
  if (relPath === COPILOT_CLOUD_FILES.setupSteps) {
    return [generateCopilotSetupStepsBody()];
  }

  return [
    generateCopilotAgentFileBody(),
    generatePreviousCopilotAgentFileBody(),
    generatePreviousCopilotAgentFileBody(true),
    generateLegacyCopilotAgentFileBody(),
  ];
}

function normalizeLineEndings(content: string): string {
  return content.replace(/\r\n/g, '\n');
}

function isCurrentCopilotCloudFile(
  relPath: CopilotCloudFile,
  content: string
): boolean {
  return normalizeLineEndings(content) === COPILOT_CLOUD_FILE_CONTENTS[relPath];
}

function isLegacyCopilotCloudFile(
  relPath: CopilotCloudFile,
  content: string
): boolean {
  return getLegacyCopilotCloudFileContents(relPath).includes(normalizeLineEndings(content));
}

function isManagedCopilotCloudFile(
  relPath: CopilotCloudFile,
  content: string
): boolean {
  return isCurrentCopilotCloudFile(relPath, content) || isLegacyCopilotCloudFile(relPath, content);
}

async function reconcileCopilotCloudFile(
  fullPath: string,
  relPath: CopilotCloudFile
): Promise<boolean> {
  const currentContent = COPILOT_CLOUD_FILE_CONTENTS[relPath];

  if (!(await FileSystemUtils.fileExists(fullPath))) {
    await FileSystemUtils.writeFile(fullPath, currentContent);
    return true;
  }

  const existingContent = await FileSystemUtils.readFile(fullPath);
  if (isCurrentCopilotCloudFile(relPath, existingContent)) {
    return false;
  }
  if (!isLegacyCopilotCloudFile(relPath, existingContent)) {
    return false;
  }

  await FileSystemUtils.writeFile(fullPath, currentContent);
  return true;
}

async function assertCreatableFilePath(filePath: string): Promise<void> {
  let candidate = path.dirname(filePath);

  while (true) {
    try {
      const stats = await fs.stat(candidate);
      if (!stats.isDirectory()) {
        throw new Error(`父路径不是目录：${candidate}`);
      }
      return;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
        throw error;
      }
    }

    const parent = path.dirname(candidate);
    if (parent === candidate) {
      throw new Error(`无法解析目录祖先：${filePath}`);
    }
    candidate = parent;
  }
}

async function assertMissingOrRegularFile(filePath: string): Promise<void> {
  try {
    const stats = await fs.stat(filePath);
    if (!stats.isFile()) {
      throw new Error(`受管理的 Copilot 路径不是常规文件：${filePath}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error;
    }
  }
}

async function classifyCopilotAgentReconciliation(
  agentPath: string,
  alternateAgentPath: string
): Promise<'reconcile' | 'skip' | 'remove-managed'> {
  if (!(await FileSystemUtils.fileExists(alternateAgentPath))) {
    return 'reconcile';
  }
  if (!(await FileSystemUtils.fileExists(agentPath))) {
    return 'skip';
  }

  const existingContent = await FileSystemUtils.readFile(agentPath);
  if (isManagedCopilotCloudFile(COPILOT_CLOUD_FILES.agent, existingContent)) {
    return 'remove-managed';
  }

  throw new Error(
    `Copilot 代理配置文件冲突：请保留 ${COPILOT_AGENT_ALTERNATE_FILE} 或 ${COPILOT_CLOUD_FILES.agent} 其中之一`
  );
}

/**
 * Reconcile Copilot cloud agent files in the project directory.
 * Creates missing files and refreshes recognized legacy generated files while
 * preserving current generated content and user customizations.
 *
 * @returns Object indicating which files were written.
 */
export async function writeCopilotCloudFiles(
  projectPath: string
): Promise<{ setupStepsWritten: boolean; agentWritten: boolean }> {
  const setupStepsPath = FileSystemUtils.resolveProjectArtifactPath(
    projectPath,
    COPILOT_CLOUD_FILES.setupSteps
  );
  const agentPath = FileSystemUtils.resolveProjectArtifactPath(
    projectPath,
    COPILOT_CLOUD_FILES.agent
  );
  const alternateAgentPath = FileSystemUtils.resolveProjectArtifactPath(
    projectPath,
    COPILOT_AGENT_ALTERNATE_FILE
  );

  await assertCreatableFilePath(setupStepsPath);
  await assertCreatableFilePath(agentPath);
  await assertMissingOrRegularFile(setupStepsPath);
  await assertMissingOrRegularFile(agentPath);
  await assertMissingOrRegularFile(alternateAgentPath);
  const agentReconciliation = await classifyCopilotAgentReconciliation(
    agentPath,
    alternateAgentPath
  );

  const setupStepsWritten = await reconcileCopilotCloudFile(
    setupStepsPath,
    COPILOT_CLOUD_FILES.setupSteps
  );
  let agentWritten = false;
  if (agentReconciliation === 'reconcile') {
    agentWritten = await reconcileCopilotCloudFile(agentPath, COPILOT_CLOUD_FILES.agent);
  } else if (agentReconciliation === 'remove-managed') {
    await fs.unlink(agentPath);
  }

  return { setupStepsWritten, agentWritten };
}

/**
 * Remove copilot cloud agent files from the project directory.
 * Used when github-copilot is deselected.
 *
 * @returns Number of files removed.
 */
export async function removeCopilotCloudFiles(projectPath: string): Promise<number> {
  let removed = 0;
  const managedPaths = Object.values(COPILOT_CLOUD_FILES).map((relPath) => ({
    relPath,
    fullPath: FileSystemUtils.resolveProjectArtifactPath(projectPath, relPath),
  }));
  for (const { fullPath } of managedPaths) {
    await assertMissingOrRegularFile(fullPath);
  }

  for (const { relPath, fullPath } of managedPaths) {
    if (await FileSystemUtils.fileExists(fullPath)) {
      const content = await FileSystemUtils.readFile(fullPath);
      if (!isManagedCopilotCloudFile(relPath, content)) {
        continue;
      }

      await fs.unlink(fullPath);
      removed++;
    }
  }

  return removed;
}

// ─────────────────────────────────────────────────────────────────────────────
// Opt-in
//
// Generating a GitHub Actions workflow into a user's `.github/` is invasive and
// ties us to Copilot's externally-owned coding-agent format, so cloud files are
// opt-in rather than an automatic side effect of selecting the Copilot tool.
// The decision is persisted in openspec/config.yaml so non-interactive
// `openspec update` (CI, agents) honors it without ever prompting.
// ─────────────────────────────────────────────────────────────────────────────

const COPILOT_CONFIG_KEY = 'githubCopilot';
const COPILOT_CLOUD_AGENT_KEY = 'cloudAgent';

/**
 * Read the persisted opt-in for Copilot cloud-file generation.
 *
 * Tri-state: `true` (opted in), `false` (explicitly opted out), or `undefined`
 * (never decided). A malformed value is treated as undecided rather than an
 * error, matching how {@link readProjectConfig} degrades on bad fields.
 */
export function readCopilotCloudOptIn(projectPath: string): boolean | undefined {
  const value = readProjectConfig(projectPath)?.githubCopilot?.cloudAgent;
  return typeof value === 'boolean' ? value : undefined;
}

/**
 * True when a managed Copilot cloud file (the current generation or a
 * recognized legacy one) already exists. Projects created before the opt-in
 * prompt existed are treated as implicitly opted in, so `openspec update`
 * keeps their files current instead of silently abandoning them.
 */
export async function hasExistingManagedCloudFiles(projectPath: string): Promise<boolean> {
  for (const relPath of Object.values(COPILOT_CLOUD_FILES)) {
    const fullPath = FileSystemUtils.resolveProjectArtifactPath(projectPath, relPath);
    if (!(await FileSystemUtils.fileExists(fullPath))) {
      continue;
    }
    const content = await FileSystemUtils.readFile(fullPath);
    if (isManagedCopilotCloudFile(relPath, content)) {
      return true;
    }
  }
  return false;
}

/**
 * Effective decision on whether to generate/refresh Copilot cloud files.
 * An explicit opt-in or opt-out always wins; when undecided, fall back to
 * whether managed files already exist (the migration path above).
 */
export async function isCopilotCloudEnabled(projectPath: string): Promise<boolean> {
  const optIn = readCopilotCloudOptIn(projectPath);
  if (typeof optIn === 'boolean') {
    return optIn;
  }
  return hasExistingManagedCloudFiles(projectPath);
}

/**
 * Persist the Copilot cloud opt-in into openspec/config.yaml.
 *
 * Uses the YAML document model rather than a re-serialize so the user's
 * existing comments, ordering, and formatting survive untouched — the config
 * file is hand-authored and heavily commented, so a lossy round-trip would be
 * its own source of toil. No-op when no config file exists yet (init creates it
 * before this is called); the caller treats persistence failures as non-fatal.
 */
export async function persistCopilotCloudOptIn(
  projectPath: string,
  value: boolean
): Promise<void> {
  const configPath = resolveConfigFilePath(projectPath);
  if (!configPath) {
    return;
  }
  const existing = await FileSystemUtils.readFile(configPath);
  const parsed = parseDocument(existing);
  // A file YAML can't parse cleanly — a multi-document stream, a tab-indented
  // syntax error — can't be edited without corrupting it, and toString() would
  // throw. Leave it untouched rather than clobber or crash; such a file is
  // already invalid, so readProjectConfig ignores it anyway.
  if (parsed.errors.length > 0) {
    return;
  }
  // `setIn(['githubCopilot', ...])` needs a top-level map. A config whose root
  // is anything else — a scalar (`null`, a bare string) or even a sequence —
  // has no map to set a key on and makes setIn throw. Such a file is already
  // invalid (readProjectConfig rejects it), so start fresh rather than crash.
  // An empty or comment-only file parses to null contents, which setIn fills in
  // while keeping the comments — so only a non-map root is discarded.
  const doc: Document =
    parsed.contents === null || isMap(parsed.contents) ? parsed : new Document();
  // The root is a map now, but the `githubCopilot` node itself may be a stray
  // scalar/sequence/null (e.g. `githubCopilot: false`) — descending into that
  // with setIn also throws. Replace any non-map node with an empty map first.
  const section = doc.getIn([COPILOT_CONFIG_KEY], true);
  if (section !== undefined && !isMap(section)) {
    doc.setIn([COPILOT_CONFIG_KEY], new YAMLMap());
  }
  doc.setIn([COPILOT_CONFIG_KEY, COPILOT_CLOUD_AGENT_KEY], value);
  await FileSystemUtils.writeFile(configPath, doc.toString());
}

/**
 * Return the managed cloud-file paths (relative to the project root) that
 * currently hold user-owned, non-managed content — i.e. files OpenSpec will
 * deliberately leave untouched. Used to tell an opted-in user that we preserved
 * their existing file rather than silently doing nothing, which is the honest
 * answer to "will this affect my existing Copilot cloud setup?".
 */
export async function findUnmanagedCloudFiles(projectPath: string): Promise<string[]> {
  const collisions: string[] = [];
  for (const relPath of Object.values(COPILOT_CLOUD_FILES)) {
    const fullPath = FileSystemUtils.resolveProjectArtifactPath(projectPath, relPath);
    if (!(await FileSystemUtils.fileExists(fullPath))) {
      continue;
    }
    const content = await FileSystemUtils.readFile(fullPath);
    if (!isManagedCopilotCloudFile(relPath, content)) {
      collisions.push(relPath);
    }
  }
  return collisions;
}

/**
 * Return the managed cloud-file paths (relative to the project root) that
 * currently exist and hold OpenSpec-generated content. Callers report this
 * rather than the intended paths, so output never claims a file that a write
 * skipped (user already owns it) or that reconciliation removed.
 */
export async function listManagedCloudFiles(projectPath: string): Promise<string[]> {
  const present: string[] = [];
  for (const relPath of Object.values(COPILOT_CLOUD_FILES)) {
    const fullPath = FileSystemUtils.resolveProjectArtifactPath(projectPath, relPath);
    if (!(await FileSystemUtils.fileExists(fullPath))) {
      continue;
    }
    const content = await FileSystemUtils.readFile(fullPath);
    if (isManagedCopilotCloudFile(relPath, content)) {
      present.push(relPath);
    }
  }
  return present;
}
